Repository hmcts/rpa-jui-webapp, pull requests merged in 2018-11, with the labels that each got.

#287 [PREVIEW] aks
  .dockerignore
  Dockerfile
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  config/application.config.js
  config/environments/local.config.js
  docker-compose.yml
  kubernetes/config.aat.yaml
  kubernetes/config.saat.yaml
  kubernetes/deployment.template.yaml
  package-lock.json
Labels: Tech Spike, [WIP] Don't Merge, ns:jui-webapp-pr-287

#285 Feature/em 735 enhance coverage
  .gitignore
  package-lock.json
  package.json
  sonar-project.properties
  src/app/shared/components/hmcts-annotation-ui-lib/components/annotation-pdf-viewer/annotation-pdf-viewer.component.html
  src/app/shared/components/hmcts-annotation-ui-lib/components/annotation-pdf-viewer/annotation-pdf-viewer.component.scss
  src/app/shared/components/hmcts-annotation-ui-lib/components/annotation-pdf-viewer/annotation-pdf-viewer.component.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/annotation-pdf-viewer/annotation-pdf-viewer.component.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comment-form/comment-form.component.html
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comment-form/comment-form.component.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comment-form/comment-form.component.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comment-item/comment-item.component.html
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comment-item/comment-item.component.scss
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comment-item/comment-item.component.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comment-item/comment-item.component.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comments.component.html
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comments.component.scss
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comments.component.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comments.component.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/contextual-toolbar/contextual-toolbar.component.html
  src/app/shared/components/hmcts-annotation-ui-lib/components/contextual-toolbar/contextual-toolbar.component.scss
  src/app/shared/components/hmcts-annotation-ui-lib/components/contextual-toolbar/contextual-toolbar.component.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/contextual-toolbar/contextual-toolbar.component.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/annotation-set.model.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/annotation-store.service.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/annotation-store.service.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/api-http.service.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/js-wrapper/pdf-annotate-wrapper.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/js-wrapper/pdf-wrapper.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/npa.service.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/pdf-adapter.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/pdf-adapter.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/pdf.service.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/pdf.service.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/utils.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/utils.ts
  src/app/shared/components/hmcts-annotation-ui-lib/hmcts-annotation-ui.module.ts
  src/public/images/em-annotate-highlight.svg
  src/public/javascripts/pdf-annotate.js
  src/public/sass/annotation-ui-theme.scss
Labels: ns:jui-webapp-pr-285

#296 Spelling error on setStoreAdapter
  src/app/shared/components/hmcts-annotation-ui-lib/data/js-wrapper/pdf-annotate-wrapper.ts
Labels: Merge once build passes

#294 Idam auth api
  Jenkinsfile_CNP
  api/services/idam-api/idam-api.js
  config/index.js
  docker/compose/docker-compose-idam.yml
  package-lock.json
  package.json
  test/integration/tests/get_jui_case_details.js
  test/integration/tests/get_jui_case_fields.js
  test/integration/tests/get_jui_case_summary.js
  test/integration/tests/get_jui_cases.js
  test/integration/tests/test.js
  test/integration/tests/utils/generateAPI.js
  test/integration/tests/utils/getToken.js
  yarn.lock
Labels: Merge once build passes, ns:jui-webapp-pr-294

#299 em health check
  api/services/em-anno-api/em-anno-api.js
  api/services/em-npa-api/em-npa-api.js
Labels: Merge once build passes, ns:jui-webapp-pr-299

#305 minor change to test url
  test/integration/tests/utils/generateAPI.js
Labels: ns:jui-webapp-pr-305

#301 Fix/angular universal annotation compat
  package.json
  src/app/shared/components/document-viewer/document-viewer.component.spec.ts
  src/app/shared/components/document-viewer/document-viewer.component.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/annotation-pdf-viewer/annotation-pdf-viewer.component.html
  src/app/shared/components/hmcts-annotation-ui-lib/components/annotation-pdf-viewer/annotation-pdf-viewer.component.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/annotation-pdf-viewer/annotation-pdf-viewer.component.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comment-item/comment-item.component.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comments.component.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comments.component.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/contextual-toolbar/contextual-toolbar.component.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/contextual-toolbar/contextual-toolbar.component.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/api-http.service.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/api-http.service.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/pdf-adapter.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/pdf-adapter.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/pdf.service.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/tool-enum.ts
  src/app/shared/components/hmcts-annotation-ui-lib/hmcts-annotation-ui.module.ts
Labels: ns:jui-webapp-pr-301

#302 Feature/em 754 stress testing
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comments.component.scss
Labels: Merge once build passes, ns:jui-webapp-pr-302

#295 fixing packages
  .nsprc
  Dockerfile
  api/case-creation/templates/divorce/financialremedy.js
  api/case-creation/templates/sscs/benefit.js
  api/case-list/assignCase.js
  api/case-list/index.js
  application.js
  kubernetes/deployment.template.yaml
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/app.server.module.ts
  src/app/domain/components/questions/create/create.component.spec.ts
  src/app/domain/components/questions/delete/delete.component.spec.ts
  src/app/domain/components/questions/edit/edit.component.spec.ts
  src/app/domain/components/questions/view/view.component.spec.ts
  src/app/domain/services/question.service.ts
  src/app/shared/components/question/question.component.html
  test/e2e/features/step_definitions/steps/dashBoard.steps.js
  yarn.lock
Labels: Merge once build passes, ns:jui-webapp-pr-295

#300 Parties tests
  Jenkinsfile_nightly
  test/e2e/config/conf.js
  test/e2e/config/smoke.conf.js
  test/e2e/features/app/login.feature
  test/e2e/features/app/makeDecision.feature
  test/e2e/features/app/parties.feature
  test/e2e/features/pages/makeDecisionPage.js
  test/e2e/features/pages/partiesPage.js
  test/e2e/features/pages/timelinePage.js
  test/e2e/features/step_definitions/steps/dashBoard.steps.js
  test/e2e/features/step_definitions/steps/logIn.steps.js
  test/e2e/features/step_definitions/steps/makeDecision.steps.js
  test/e2e/features/step_definitions/steps/parties.steps.js
  test/e2e/support/hooks.js
  yarn.lock
Labels: Fixes Required, Merge once build passes, ns:jui-webapp-pr-300

#306 Tests: Updating smoke.conf.js file & Updating tests
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  test/e2e/config/conf.js
  test/e2e/config/smoke.conf.js
  test/e2e/features/app/dashBoard.feature
  test/e2e/features/app/login.feature
  test/e2e/features/app/questions.feature
  test/e2e/features/pages/caseSummaryPage.js
  test/e2e/features/pages/questionsPage.js
  test/e2e/features/step_definitions/steps/dashBoard.steps.js
  test/e2e/features/step_definitions/steps/logIn.steps.js
  test/e2e/features/step_definitions/steps/questions.steps.js
  test/e2e/support/world.js
  yarn.lock
Labels: Fixes Required, ns:jui-webapp-pr-306

#281 [WIP] linked case
  api/case-list/index.js
  api/case/index.js
  api/case/templates/sscs/benefit.js
  api/events/templates/index.js
  api/lib/processors/case-state-model.js
  api/lib/processors/case-state-model.spec.js
  api/lib/processors/case-state-util.js
Labels: [WIP] Don't Merge, ns:jui-webapp-pr-281

#315 move to folder
  api/controllers/auth/auth.spec.js
  api/controllers/auth/index.js
  api/controllers/case-creation/index.js
  api/controllers/case-creation/state-map-exmaples/div-state.txt
  api/controllers/case-creation/state-map-exmaples/fr-state.txt
  api/controllers/case-creation/state-map-exmaples/sscs-state.txt
  api/controllers/case-creation/templates/cmc/moneyclaimcase.js
  api/controllers/case-creation/templates/default/default.js
  api/controllers/case-creation/templates/divorce/divorce.js
  api/controllers/case-creation/templates/divorce/financialremedy.js
  api/controllers/case-creation/templates/index.js
  api/controllers/case-creation/templates/probate/grantofrepresentation.js
  api/controllers/case-creation/templates/sscs/benefit.js
  api/controllers/case-list/assignCase.js
  api/controllers/case-list/case-list-spec-data.js
  api/controllers/case-list/case-list.spec.js
  api/controllers/case-list/index.js
  api/controllers/case-list/templates/cmc/moneyclaimcase.json
  api/controllers/case-list/templates/default/default.json
  api/controllers/case-list/templates/divorce/divorce.json
  api/controllers/case-list/templates/divorce/financialremedy.json
  api/controllers/case-list/templates/index.js
  api/controllers/case-list/templates/probate/grantofrepresentation.json
  api/controllers/case-list/templates/sscs/benefit.json
  api/controllers/case/case.spec.js
  api/controllers/case/index.js
  api/controllers/case/templates/cmc/moneyclaimcase.js
  api/controllers/case/templates/default/default.js
  api/controllers/case/templates/divorce/divorce.js
  api/controllers/case/templates/divorce/financialremedy.js
  api/controllers/case/templates/index.js
  api/controllers/case/templates/probate/grantofrepresentation.js
  api/controllers/case/templates/sscs/benefit.js
  api/controllers/decisions/cohDecisions.js
  api/controllers/decisions/index.js
  api/controllers/decisions/state.js
  api/controllers/decisions/state_meta.js
  api/controllers/decisions/translate.js
  api/controllers/dev/decisions.js
  api/controllers/dev/test.js
  api/controllers/documents/index.js
  api/controllers/events/event.spec.js
  api/controllers/events/index.js
  api/controllers/events/templates/cmc/moneyclaimcase.json
  api/controllers/events/templates/default.json
  api/controllers/events/templates/divorce/divorce.json
  api/controllers/events/templates/divorce/financialremedy.json
  api/controllers/events/templates/index.js
  api/controllers/events/templates/probate/grantofrepresentation.json
  api/controllers/events/templates/sscs/benefit.json
  api/controllers/hearings/index.js
  api/controllers/questions/index.js
  api/controllers/questions/question.spec.js
  api/index.js
Labels: ns:jui-webapp-pr-315

#320 changed token url to idam api
  test/integration/tests/utils/getToken.js
Labels: ns:jui-webapp-pr-320

#317 Fix: Separating mock data and Refactoring overall components to fix NG life-cycle
  README.md
  package-lock.json
  src/app/domain/case-viewer/components/case-viewer/case-viewer.component.html
  src/app/domain/case-viewer/components/case-viewer/case-viewer.component.spec.ts
  src/app/domain/case-viewer/components/case-viewer/case-viewer.component.ts
  src/app/domain/case-viewer/components/parties-panel/mock/parties-panel.mock.ts
  src/app/domain/case-viewer/components/parties-panel/parties-panel.component.spec.ts
  src/app/domain/case-viewer/components/parties-panel/parties-panel.component.ts
  src/app/domain/case-viewer/components/questions-panel/mock/mock-questions.mock.ts
  src/app/domain/case-viewer/components/questions-panel/questions-panel.component.spec.ts
  src/app/domain/case-viewer/components/summary-panel/mock/summary-panel.mock.ts
  src/app/domain/case-viewer/components/summary-panel/models/elements.module.ts
  src/app/domain/case-viewer/components/summary-panel/summary-panel.component.html
  src/app/domain/case-viewer/components/summary-panel/summary-panel.component.spec.ts
  src/app/domain/case-viewer/components/summary-panel/summary-panel.component.ts
  src/app/domain/case-viewer/components/timeline-panel/timeline-panel.component.spec.ts
  src/app/domain/components/casebar/casebar.component.html
  src/app/domain/components/casebar/casebar.component.spec.ts
  src/app/domain/components/casebar/casebar.component.ts
  src/app/domain/components/casebar/mock/case.mock.ts
  src/app/domain/models/section_fields.ts
  src/app/domain/services/case.service.ts
  src/app/enviorment.mock.ts
  src/app/hmcts/components/hmcts-sub-navigation/hmcts-sub-navigation.component.html
  src/app/hmcts/components/hmcts-sub-navigation/hmcts-sub-navigation.component.spec.ts
  src/app/hmcts/components/hmcts-sub-navigation/hmcts-sub-navigation.component.ts
  src/app/hmcts/components/hmcts-sub-navigation/mock/hmcts-sub-navigation.mock.ts
  src/app/hmcts/models/nav.ts
  src/app/routing/pages/generic-page/check-your-answers/check-your-answers.component.ts
  src/app/routing/pages/hearings/check-hearing/check-hearing.component.spec.ts
  src/app/routing/pages/hearings/check-hearing/mock/check-hearing.mock.ts
  src/app/routing/pages/hearings/create-hearing/create-hearing.component.spec.ts
  src/app/routing/pages/hearings/create-hearing/create-hearing.component.ts
  src/app/routing/pages/hearings/create-hearing/mock/create-hearing.mock.ts
  src/app/routing/pages/hearings/root/root.component.ts
  src/app/routing/pages/modules/case.ts
  src/app/routing/pages/view-case/mock/view-case.mock.ts
  src/app/routing/pages/view-case/view-case.component.html
  src/app/routing/pages/view-case/view-case.component.spec.ts
  src/app/routing/pages/view-case/view-case.component.ts
  src/app/routing/pages/view-case/view-case.services.ts
  src/app/routing/resolve/case.resolve.ts
  src/app/routing/routing.module.ts
  src/app/shared/components/table/table.component.html
  src/app/shared/components/table/table.component.ts
  src/app/shared/components/table/table.ts
  test/karma.conf.js
  yarn.lock
Labels: ns:jui-webapp-pr-317

#321 Introducing husky a github pre-commit & pre-push hooks
  .huskyrc
  package.json
  src/app/auth/auth.service.spec.ts
  src/app/config.service.server.ts
  src/app/config.service.ts
  src/app/domain/case-viewer/case-viewer.module.ts
  src/app/domain/case-viewer/components/parties-panel/mock/parties-panel.mock.ts
  src/app/domain/case-viewer/components/questions-panel/questions-panel.component.spec.ts
  src/app/domain/case-viewer/components/summary-panel/models/elements.module.ts
  src/app/domain/case-viewer/components/summary-panel/summary-panel.component.ts
  src/app/domain/components/questions/create/create.component.ts
  src/app/domain/models/section_fields.ts
  src/app/domain/services/case.service.ts
  src/app/domain/services/decision.service.spec.ts
  src/app/domain/services/decision.service.ts
  src/app/forms/components/form/form.component.ts
  src/app/forms/components/radio-buttons/radio-buttons.component.spec.ts
  src/app/forms/components/radio-buttons/radio-buttons.component.ts
  src/app/forms/components/text/text.component.spec.ts
  src/app/forms/components/textarea/textarea.component.spec.ts
  src/app/forms/forms.module.ts
  src/app/hmcts/components/hmcts-sub-navigation/hmcts-sub-navigation.component.spec.ts
  src/app/hmcts/components/hmcts-sub-navigation/mock/hmcts-sub-navigation.mock.ts
  src/app/hmcts/models/nav.ts
  src/app/routing/pages/decisions/check-decision/check-decision.component.spec.ts
  src/app/routing/pages/decisions/check-decision/check-decision.component.ts
  src/app/routing/pages/decisions/create-decision/create-decision.component.spec.ts
  src/app/routing/pages/decisions/create-decision/create-decision.component.ts
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.spec.ts
  src/app/routing/pages/decisions/fr/draft-consent-order/draft-consent-order.component.ts
  src/app/routing/pages/decisions/fr/hearing-details/hearing-details.component.ts
  src/app/routing/pages/decisions/fr/reasons-co-not-approved/reasons-co-not-approved.component.ts
  src/app/routing/pages/hearings/check-hearing/check-hearing.component.ts
  src/app/routing/pages/hearings/check-hearing/mock/check-hearing.mock.ts
  src/app/routing/pages/hearings/create-hearing/mock/create-hearing.mock.ts
  src/app/routing/pages/modules/case.ts
  src/app/routing/pages/view-case/mock/view-case.mock.ts
  src/app/routing/resolve/case.resolve.spec.ts
  src/app/routing/resolve/decision.resolve.spec.ts
  src/app/shared/components/document-upload/document-upload.component.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/annotation-store.service.ts
  src/app/shared/components/table/mock/table.mock.ts
  src/app/shared/components/table/table.component.spec.ts
  src/app/shared/components/table/table.component.ts
  src/app/shared/components/table/table.ts
  src/app/shared/services/forms.service.ts
  src/app/shared/services/validation.service.ts
  src/server.main.ts
  tslint.json
Labels: ns:jui-webapp-pr-321

#322 horizontal rendering fix
  src/app/shared/components/hmcts-annotation-ui-lib/data/pdf.service.ts
Labels: ns:jui-webapp-pr-322

#324 EM-915-Add stacking of comments to avoid overlapping.
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comment-item/comment-item.component.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comments.component.html
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comments.component.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comments.component.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/utils.ts
Labels: ns:jui-webapp-pr-324

#326 Feature/document upload node layer
  api/controllers/documents/index.js
  api/lib/request/request.js
  api/services/dm-store-api/dm-store-api.js
  package-lock.json
  package.json
  src/app/shared/components/document-list/document-list.component.ts
  src/app/shared/components/document-upload/document-upload.component.html
  src/app/shared/services/documentStore/document-store.service.ts
  yarn.lock
Labels: ns:jui-webapp-pr-326

#327 ignore https
  test/integration/tests/test.js
Labels: ns:jui-webapp-pr-327

#329 Feature/em 915 annotation blocks stacked 2
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comment-item/comment-item.component.html
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comment-item/comment-item.component.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comment-item/comment-item.component.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comments.component.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comments.component.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/annotation-store.service.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/utils.spec.ts
  src/app/shared/components/hmcts-annotation-ui-lib/data/utils.ts
  yarn.lock
Labels: ns:jui-webapp-pr-329

#325 Resizing the annotation comment box
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comment-item/comment-item.component.html
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comment-item/comment-item.component.scss
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comment-item/comment-item.component.ts
  src/app/shared/components/hmcts-annotation-ui-lib/components/comments/comments.component.spec.ts
Labels: ns:jui-webapp-pr-325

#333 Feature/fixing validation on master
  api/controllers/decisions/state_meta.js
  src/app/routing/pages/decisions/fr/reasons-co-not-approved/reasons-co-not-approved.component.ts
  src/app/shared/components/fieldset/fieldset.component.html
  src/app/shared/components/fieldset/fieldset.component.ts
  src/app/shared/components/jui-form-elements/jui-form-elements.component.html
  src/app/shared/components/textareas/textareas.component.html
  src/app/shared/services/forms.service.ts
  src/app/shared/services/validation.service.spec.ts
  src/app/shared/services/validation.service.ts
  src/app/shared/services/validation.typescript.ts
Labels: ns:jui-webapp-pr-333

#343 Revert "introduce Feature/error handling (#336)"
  angular.json
  package-lock.json
  projects/static-pages/karma.conf.js
  projects/static-pages/ng-package.json
  projects/static-pages/package.json
  projects/static-pages/src/lib/containers/gateway-timeout/gateway-timeout.component.html
  projects/static-pages/src/lib/containers/gateway-timeout/gateway-timeout.component.spec.ts
  projects/static-pages/src/lib/containers/gateway-timeout/gateway-timeout.component.ts
  projects/static-pages/src/lib/containers/not-found/not-found.component.html
  projects/static-pages/src/lib/containers/not-found/not-found.component.scss
  projects/static-pages/src/lib/containers/not-found/not-found.component.spec.ts
  projects/static-pages/src/lib/containers/not-found/not-found.component.ts
  projects/static-pages/src/lib/static-pages.module.ts
  projects/static-pages/src/lib/static-pages.route.ts
  projects/static-pages/src/public_api.ts
  projects/static-pages/src/test.ts
  projects/static-pages/tsconfig.lib.json
  projects/static-pages/tsconfig.spec.json
  projects/static-pages/tslint.json
  src/app/app.module.ts
  src/app/auth/auth-inteceptor.ts
  src/app/auth/auth.service.spec.ts
  src/app/domain/services/case.service.ts
  src/app/routing/pages/generic-page/error-service-unavailable/error-service-unavailable.component.html
  src/app/routing/pages/generic-page/error-service-unavailable/error-service-unavailable.component.scss
  src/app/routing/pages/generic-page/error-service-unavailable/error-service-unavailable.component.spec.ts
  src/app/routing/pages/generic-page/error-service-unavailable/error-service-unavailable.component.ts
  src/app/routing/routing.module.ts
  src/app/shared/components/tabs/tabs.component.spec.ts
  tsconfig.json
  yarn.lock
Labels: ns:jui-webapp-pr-343
