Repository hmcts/rpa-jui-webapp, pull requests merged in 2018-12, with the labels that each got.

#367 changed preview config to preview from mock
  Jenkinsfile_CNP
  config/index.ts
  test/e2e/config/conf.js
  test/e2e/config/smoke.conf.js
Labels: ns:jui-webapp-pr-367

#335 Feature/em 917 updated comment box css
  src/app/shared/components/hmcts-em-viewer-ui/data/annotation-store.service.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/annotation-store.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/comments/comment-item/comment-item.component.html
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/comments/comment-item/comment-item.component.scss
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/comments/comment-item/comment-item.component.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/comments/comment-item/comment-item.component.ts
Labels: ns:jui-webapp-pr-335

#379 Mocha and chai v2
  .gitignore
  api/api.spec.ts
  api/controllers/auth/auth.spec.ts
  api/controllers/auth/index.ts
  api/controllers/decisions/decisions.ts
  api/controllers/decisions/state.ts
  api/index.ts
  api/package.json
  api/test/mocha.opts
  api/tsconfig.json
  application.ts
  package-lock.json
  package.json
  server.ts
  src/tsconfig.spec.json
  support/old-tests/api/controllers/case-creation/case-creation.spec.ts
  support/old-tests/api/controllers/case-list/case-list-spec-data.ts
  support/old-tests/api/controllers/case-list/case-list.spec.ts
  support/old-tests/api/controllers/case/case.spec.ts
  support/old-tests/api/controllers/documents/documents.spec.ts
  support/old-tests/api/controllers/events/event.spec.ts
  support/old-tests/api/controllers/questions/question.spec.ts
  support/old-tests/api/lib/middleware/auth.spec.ts
  support/old-tests/api/lib/middleware/service-token.spec.ts
  support/old-tests/api/lib/processors/case-state-model.spec.ts
  support/old-tests/api/lib/processors/case-state-util.spec.ts
  support/old-tests/api/lib/processors/case-status-processor.spec.ts
  support/old-tests/api/lib/processors/document-processor.spec.ts
  support/old-tests/api/lib/processors/value-processor.spec.ts
  support/old-tests/api/services/bar-api.spec.ts
  support/old-tests/api/services/ccd-def-api.spec.ts
  support/old-tests/api/services/ccd-store.spec.ts
  support/old-tests/api/services/coh-cor-api.spec.ts
  support/old-tests/api/services/dm-store-api.spec.ts
  support/old-tests/api/services/draft-store-api.spec.ts
  support/old-tests/api/services/em-anno-api.spec.ts
  support/old-tests/api/services/em-npa-api.spec.ts
  support/old-tests/api/services/fee-api.spec.ts
  support/old-tests/api/services/idam-api.spec.ts
  support/old-tests/api/services/pay-api.spec.ts
  support/old-tests/api/services/service-auth-provider-api.spec.ts
  support/old-tests/utilities/headerUtilities.spec.ts
  tsconfig.json
  yarn.lock
Labels: ns:jui-webapp-pr-379

#383 enable console logs for tests
  Jenkinsfile_CNP
  test/e2e/config/conf.js
  test/e2e/config/crossbrowser.conf.js
  test/e2e/config/smoke.conf.js
Labels: ns:jui-webapp-pr-383

#384 Aa mocha and chai
  .gitignore
  api/controllers/case-list/case-list-spec-data.ts
  api/controllers/case-list/case-list.spec.ts
  api/controllers/case/case.spec.ts
  api/services/bar-api/bar-api.spec.ts
  api/services/ccd-def-api/ccd-def-api.spec.ts
  api/services/ccd-store-api/ccd-store.spec.ts
  api/services/coh-cor-api/coh-cor-api.spec.ts
  api/services/dm-store-api/dm-store-api.spec.ts
  api/services/draft-store-api/draft-store-api.spec.ts
  api/services/em-anno-api/em-anno-api.spec.ts
  api/services/em-anno-api/em-anno-api.ts
  api/services/em-npa-api/em-npa-api.spec.ts
  api/services/fee-api/fee-api.spec.ts
  api/services/idam-api/idam-api.spec.ts
  api/services/pay-api/pay-api.spec.ts
  api/services/service-auth-provider-api/service-auth-provider-api.spec.ts
  api/yarn.lock
  support/old-tests/api/controllers/case-list/case-list-spec-data.ts
  support/old-tests/api/controllers/case-list/case-list.spec.ts
  support/old-tests/api/controllers/case/case.spec.ts
  support/old-tests/api/services/bar-api.spec.ts
  support/old-tests/api/services/ccd-def-api.spec.ts
  support/old-tests/api/services/ccd-store.spec.ts
  support/old-tests/api/services/coh-cor-api.spec.ts
  support/old-tests/api/services/dm-store-api.spec.ts
  support/old-tests/api/services/draft-store-api.spec.ts
  support/old-tests/api/services/em-anno-api.spec.ts
  support/old-tests/api/services/em-npa-api.spec.ts
  support/old-tests/api/services/fee-api.spec.ts
  support/old-tests/api/services/idam-api.spec.ts
  support/old-tests/api/services/pay-api.spec.ts
  support/old-tests/api/services/service-auth-provider-api.spec.ts
Labels: ns:jui-webapp-pr-384

#387 change to startup script
  package.json
Labels: ns:jui-webapp-pr-387

#401 Adding dynamic titles and some accessibility fixes + loading spinner and secondary nav fix rui 1282
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/domain/components/header/header.component.html
  src/app/domain/components/header/header.component.spec.ts
  src/app/domain/components/header/header.component.ts
  src/app/domain/components/search-result/search-result.component.html
  src/app/domain/components/search-result/search-result.component.scss
  src/app/domain/components/search-result/search-result.component.ts
  src/app/hmcts/components/hmcts-primary-navigation/hmcts-primary-navigation.component.html
  src/app/hmcts/components/hmcts-primary-navigation/hmcts-primary-navigation.component.spec.ts
  src/app/hmcts/components/hmcts-sub-navigation/hmcts-sub-navigation.component.html
  src/app/routing/pages/generic-page/dashboard/dashboard.component.html
  src/app/routing/pages/generic-page/dashboard/dashboard.component.ts
  src/app/routing/pages/view-case/view-case.component.ts
  src/app/shared/components/document/case-file-tool-bar/case-file-tool-bar.component.html
  src/app/shared/components/document/case-file-tool-bar/case-file-tool-bar.component.ts
Labels: ns:jui-webapp-pr-401

#406 fix node test watch
  api/package.json
Labels: ns:jui-webapp-pr-406

#394 Pull through the document modified date to show to the user.
  src/app/domain/case-viewer/components/document-panel/document-panel.component.ts
  src/app/shared/components/document/case-file-tree-list/case-file-tree-list.component.html
  src/app/shared/components/document/case-file-tree-list/case-file-tree-list.component.ts
Labels: ns:jui-webapp-pr-394

#414 bug fix for case files CTAs colors and wrong active state
  src/app/shared/components/document/case-file-tool-bar/case-file-tool-bar.component.html
  src/app/shared/components/document/case-file-tool-bar/case-file-tool-bar.component.ts
  src/public/components/casefile/_casefile-3.scss
Labels: ns:jui-webapp-pr-414

#417 Fix: Removing Representative and fixing text
  api/controllers/case/templates/sscs/benefit.ts
Labels: ns:jui-webapp-pr-417

#400 hide image rotate functionality
  src/app/shared/components/hmcts-em-viewer-ui/viewers/image-viewer/image-viewer.component.html
Labels: ns:jui-webapp-pr-400

#422 stacking comments overflow height set to auto
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/comments/comments.component.scss
Labels: ns:jui-webapp-pr-422

#403 Reimplement commented out unit tests
  src/app/shared/components/hmcts-em-viewer-ui/data/annotation-store.service.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/annotation-store.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/document-viewer/document-viewer.service.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/comments/comments.component.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/contextual-toolbar/contextual-toolbar.component.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/contextual-toolbar/contextual-toolbar.component.ts
Labels: ns:jui-webapp-pr-403

#415 Feature/em 991 logging service
  src/app/shared/components/hmcts-em-viewer-ui/data/annotation-store.service.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/annotation-store.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/api-http.service.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/api-http.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/npa.service.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/npa.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/pdf-adapter.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/pdf-adapter.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/pdf.service.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/pdf.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/document-viewer/document-viewer.component.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/document-viewer/document-viewer.component.ts
  src/app/shared/components/hmcts-em-viewer-ui/document-viewer/document-viewer.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/hmcts-em-viewer-ui.module.ts
  src/app/shared/components/hmcts-em-viewer-ui/logging/em-logger.service.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/logging/em-logger.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/annotation-pdf-viewer.component.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/annotation-pdf-viewer.component.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/comments/comment-item/comment-item.component.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/comments/comment-item/comment-item.component.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/comments/comments.component.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/comments/comments.component.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/contextual-toolbar/contextual-toolbar.component.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/contextual-toolbar/contextual-toolbar.component.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/image-viewer/image-viewer.component.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/image-viewer/image-viewer.component.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/viewer-factory.service.ts
  yarn.lock
Labels: ns:jui-webapp-pr-415

#429 RIUI -1208 - disable add question after click
  log/access.log
  log/access.log-2018-12-10
  log/app.log
  log/errors.log~HEAD
  log/errors.log~RIUI-1208-disableSubsequentClicks
  src/app/domain/components/questions/check/check.component.html
  src/app/domain/components/questions/check/check.component.ts
  src/app/domain/components/questions/create/create.component.html
  src/app/domain/components/questions/create/create.component.ts
  src/app/shared/components/custombuttons/custombuttons.component.html
  src/app/shared/components/custombuttons/custombuttons.component.scss
  src/app/shared/components/custombuttons/custombuttons.component.scss~HEAD
  src/app/shared/components/custombuttons/custombuttons.component.scss~RIUI-1208-disableSubsequentClicks
  src/app/shared/components/custombuttons/custombuttons.component.spec.ts
  src/app/shared/components/custombuttons/custombuttons.component.spec.ts~HEAD
  src/app/shared/components/custombuttons/custombuttons.component.spec.ts~RIUI-1208-disableSubsequentClicks
  src/app/shared/components/custombuttons/custombuttons.component.ts
  src/app/shared/shared.module.ts
  src/index.html
Labels: ns:jui-webapp-pr-429

#435 adding EmLoggerService dependency to fix test
  src/app/shared/components/hmcts-em-viewer-ui/document-viewer/document-viewer.service.spec.ts
Labels: ns:jui-webapp-pr-435

#426 changing readme file and adding aria label for textarea
  README.md
  src/app/shared/components/textareas/textareas.component.html
Labels: ns:jui-webapp-pr-426

#433 Feature/hearing fix
  api/constants/cohConstants.ts
  api/controllers/decisions/cohDecisions.ts
  api/services/coh.spec.ts
  api/services/coh.ts
  package-lock.json
  src/app/domain/services/hearing.service.ts
  src/app/routing/pages/hearings/check-hearing/check-hearing.component.html
  src/app/routing/pages/hearings/check-hearing/check-hearing.component.ts
  src/app/routing/pages/hearings/create-hearing/create-hearing.component.html
  src/app/routing/pages/hearings/create-hearing/create-hearing.component.ts
  src/app/routing/pages/hearings/hearing-confirmation/hearing-confirmation.component.html
Labels: ns:jui-webapp-pr-433

#444 feat: (DIVORCE/FinancialRemedyMVP2) Displaying "assigntoJudge" property on the front end
  api/controllers/case-list/index.ts
  src/app/shared/components/table/table.component.html
  src/app/shared/components/table/table.component.ts
Labels: ns:jui-webapp-pr-444

#443 enabled node coverage report
  Jenkinsfile_CNP
  package.json
Labels: ns:jui-webapp-pr-443

#442 Bug/ccd def hammer
  api/index.ts
  api/services/ccd-def-api/ccd-def-api.spec.ts
  api/services/ccd-def-api/ccd-def-api.ts
Labels: ns:jui-webapp-pr-442

#446 bugfix RIUI-1355 - update title header set award date
  api/controllers/decisions/sscs/templates/benefit/setAwardDates.ts
Labels: ns:jui-webapp-pr-446

#434 Feature/em 991 logging service
  src/app/shared/components/hmcts-em-viewer-ui/data/annotation-store.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/pdf-adapter.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/pdf.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/document-viewer/document-viewer.component.ts
  src/app/shared/components/hmcts-em-viewer-ui/document-viewer/document-viewer.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/logging/em-logger.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/image-viewer/image-viewer.component.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/viewer-factory.service.ts
Labels: ns:jui-webapp-pr-434

#430 rebased_enabled_functional_tests
  package.json
  test/e2e/config/conf.js
  test/e2e/config/smoke.conf.js
  test/e2e/features/app/caseFile.feature
  test/e2e/features/app/dashBoard.feature
  test/e2e/features/app/login.feature
  test/e2e/features/pages/dashBoardPage.js
  test/e2e/features/pages/timelinePage.js
  test/e2e/features/step_definitions/steps/caseSummary.steps.js
  test/e2e/features/step_definitions/steps/dashBoard.steps.js
  test/e2e/features/step_definitions/steps/recentEvents.steps.js
  test/e2e/support/constants.js
Labels: ns:jui-webapp-pr-430

#451 Fix: RIUI- 1364 - Passing input values to component
  src/app/shared/components/document/case-file/case-file.component.html
Labels: ns:jui-webapp-pr-451

#449 Refactor/riui 1346 authentication and tests from master
  .gitignore
  api/controllers/auth/auth.spec.ts
  api/controllers/auth/index.ts
  api/lib/util.ts
  api/services/idam-api/idam-api.ts
  api/tsconfig.json
  package.json
Labels: ns:jui-webapp-pr-449
