Repository hmcts/rpa-jui-webapp, pull requests merged in 2019-04, with the labels that each got.

#878 Feature/coh unit tests
  api/controllers/decisions/cohDecisions.ts
  api/services/coh.spec.ts
  api/services/coh.ts
Labels: ns:jui-webapp-pr-878

#876 Enable functional tests
  config/environments/preview.config.ts
  test/e2e/config/conf.js
  test/e2e/config/smoke.conf.js
Labels: ns:jui-webapp-pr-876

#885 Demo switch sidam
  config/environments/demo.config.ts
Labels: ns:jui-webapp-pr-885

#888 unit test fix test
  package.json
  src/app/forms/components/text-editor/text-editor.component.spec.ts
  src/app/forms/forms.module.spec.ts
  src/app/forms/forms.module.ts
Labels: ns:jui-webapp-pr-888

#893 tests_fixed_sidam
  test/e2e/features/pages/loginPage.js
  test/e2e/features/step_definitions/steps/logIn.steps.js
Labels: ns:jui-webapp-pr-893

#887 Removing visual error messages, error stack is still logged out to th…
  src/app/domain/components/search-result/search-result.component.html
  src/app/domain/components/search-result/search-result.component.ts
Labels: ns:jui-webapp-pr-887

#894 Fixing DEMO env Unit test coverage
  src/app/config.service.spec.ts
Labels: ns:jui-webapp-pr-894

#886 Bugfix/riui 1623 multiple calls to ccd
  api/controllers/case-list/index.spec.ts
  api/controllers/case-list/index.ts
  api/lib/config/errorConstants.ts
  api/lib/config/refCaselistFilters.ts
  api/lib/filters.spec.ts
  api/lib/filters.ts
Labels: ns:jui-webapp-pr-886

#890 Adding liveness check DON'T MERGE
  application.ts
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-890

#898 bugfix for make decision flow
  api/services/coh.spec.ts
  api/services/coh.ts
Labels: ns:jui-webapp-pr-898

#899 form.component.ts unit tests fixed
  src/app/forms/components/form/form.component.spec.ts
  src/app/forms/components/form/form.component.ts
Labels: ns:jui-webapp-pr-899

#900 Bug/riui 1610 enable roles
  api/controllers/auth/index.ts
  package-lock.json
  src/app/auth/auth.service.spec.ts
  src/app/auth/auth.service.ts
Labels: ns:jui-webapp-pr-900

#896 Add liveness check
  application.ts
Labels: ns:jui-webapp-pr-896

#902 RIUI-1653 - textareas.component.ts - Unit tests fixed
  src/app/shared/components/textareas/textareas.component.spec.ts
  src/app/shared/components/textareas/textareas.component.ts
  src/app/shared/services/validation.service.ts
Labels: ns:jui-webapp-pr-902

#903 RIUI-1666 - case.service.ts is 100% coverage now
  src/app/domain/services/case.service.spec.ts
  src/app/domain/services/case.service.ts
Labels: ns:jui-webapp-pr-903

#907 Feature/ccd store unit tests
  api/services/ccd-store-api/ccd-store.spec.ts
Labels: ns:jui-webapp-pr-907

#911 Casebar component unit tests 100% now, exchange service is 100% now as well
  src/app/domain/components/casebar/casebar.component.spec.ts
  src/app/domain/components/casebar/casebar.component.ts
Labels: ns:jui-webapp-pr-911

#914 RIUI-1470-deploy-prod-fix
  infrastructure/main.tf
Labels: ns:jui-webapp-pr-914

#912 Bug/fz unit tests cases
  api/controllers/case-list/assignCase.ts
  api/controllers/case-list/assing-case.spec.ts
  api/controllers/case-list/case-list-spec-data.spec.ts
  api/controllers/case-list/case-list-spec-data.ts
  api/controllers/case/index.spec.ts
  api/controllers/case/index.ts
Labels: ns:jui-webapp-pr-912

#915 tests for lib http
  api/lib/config/error-const.spec.ts
Labels: ns:jui-webapp-pr-915

#918 config.service.server.ts excluded from sonar report
  sonar-project.properties
  src/app/config.service.server.ts
Labels: ns:jui-webapp-pr-918

#920 COH specs and 'this' context for tests - DO NOT MERGE YET
  api/services/coh.spec.ts
  api/services/coh.ts
Labels: ns:jui-webapp-pr-920

#925 RIUI-1558 - (subtask) Config service unit tests code coverage fix
  package.json
  src/app/config.service.spec.ts
  src/app/config.service.ts
Labels: ns:jui-webapp-pr-925

#921 Feature/controller events unit tests
  api/controllers/events/index.spec.ts
  api/controllers/events/index.ts
Labels: ns:jui-webapp-pr-921

#926 TEST: Controllers: Decisions: Index 100%: #1673
  api/controllers/decisions/index.spec.ts
Labels: ns:jui-webapp-pr-926

#910 added full functional tests
  test/e2e/config/conf.js
  test/e2e/features/app/dashBoard.feature
  test/e2e/features/app/dashBoard.min.feature
  test/e2e/features/app/login.feature
  test/e2e/features/app/parties.feature
  test/e2e/features/app/questions.feature
  test/e2e/features/app/summary.feature
  test/e2e/features/step_definitions/steps/logIn.steps.js
Labels: ns:jui-webapp-pr-910

#927 Bug/test services riui 1684
  api/services/serviceAuth.spec.ts
  api/services/serviceAuth.ts
Labels: ns:jui-webapp-pr-927

#928 enabled smoke tests and changed constant values
  test/e2e/config/smoke.conf.js
  test/e2e/features/step_definitions/steps/logIn.steps.js
  test/e2e/support/constants.js
Labels: ns:jui-webapp-pr-928

#929 Test/increase node coverage case decisions
  api/controllers/decisions/divorce/index.spec.ts
  api/controllers/decisions/divorce/index.ts
Labels: ns:jui-webapp-pr-929

#909 [BLOCKED]: Tests middleware
  api/lib/middleware/responseRequest.ts
  api/lib/middleware/securityHeaders.spec.ts
  api/lib/middleware/securityHeaders.ts
  api/lib/middleware/serviceToken.spec.ts
  api/lib/middleware/serviceToken.ts
  api/package.json
  package-lock.json
Labels: ns:jui-webapp-pr-909

#931 Feature/1667 no cases
  api/controllers/case-list/index.ts
  api/lib/case-list/case-list-helper.spec.ts
  api/lib/case-list/case-list-helper.ts
  api/lib/processors/case-state-util.ts
  src/app/domain/components/search-result/search-result.component.html
  src/app/domain/components/search-result/search-result.component.spec.ts
  src/app/domain/components/search-result/search-result.component.ts
  src/app/domain/services/case.service.ts
Labels: ns:jui-webapp-pr-931

#932 RIUI-1746 Show local time in Time line component render output.
  src/app/domain/case-viewer/components/timeline-panel/timeline-panel.component.html
  src/app/domain/components/casebar/casebar.component.ts
  src/app/hmcts/components/hmcts-timeline/hmcts-timeline.component.html
  src/app/hmcts/components/hmcts-timeline/hmcts-timeline.component.ts
Labels: ns:jui-webapp-pr-932

#934 fix: fixed issue where we were only testing the emptiness of first el…
  api/services/ccd-store-api/ccd-store.ts
Labels: ns:jui-webapp-pr-934
