Repository hmcts/rpa-jui-webapp, pull requests merged in 2019-05, with the labels that each got.

#940 RIUI-1781 fixed
  api/controllers/decisions/sscs/templates/benefit/setAwardDates.ts
  src/app/shared/services/validation.service.spec.ts
  src/app/shared/services/validation.service.ts
  test/karma.conf.js
Labels: ns:jui-webapp-pr-940

#941 tests: added tests for bar and refactor
  api/services/bar.spec.ts
  api/services/bar.ts
Labels: ns:jui-webapp-pr-941

#939 tests: added tests for documents and refactor
  api/controllers/documents/index.spec.ts
  api/controllers/documents/index.ts
  api/index.ts
Labels: ns:jui-webapp-pr-939

#936 fix: fixed issue where the service could return no cases and error no…
  api/controllers/case-list/index.spec.ts
  api/controllers/case-list/index.ts
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.spec.ts
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.ts
  test/e2e/config/conf.js
  test/e2e/config/crossbrowser.conf.js
  test/e2e/config/smoke.conf.js
Labels: ns:jui-webapp-pr-936

#944 RIUI-1794 bug fixed
  src/app/routing/pages/decisions/check-decision/check-decision.component.html
  src/app/routing/pages/hearings/hearing-confirmation/hearing-confirmation.component.html
  test/e2e/config/conf.js
  test/e2e/config/smoke.conf.js
Labels: ns:jui-webapp-pr-944

#945 crossbrowser new saucelabs host added
  test/e2e/config/crossbrowser.conf.js
Labels: ns:jui-webapp-pr-945

#946 RIUI-1800 fixed
  src/app/shared/components/question-list/question-list.component.html
Labels: ns:jui-webapp-pr-946

#947 Feature/riui 1799 well form questions
  src/app/domain/components/questions/create/create.component.ts
  src/app/domain/components/questions/edit/edit.component.ts
  src/app/domain/services/question.service.spec.ts
  src/app/domain/services/question.service.ts
Labels: ns:jui-webapp-pr-947

#949 crossbrowser address tests enabled
  README.md
  test/e2e/config/conf.js
  test/e2e/config/crossbrowser.conf.js
  test/e2e/config/smoke.conf.js
Labels: ns:jui-webapp-pr-949

#951 upgrading protractor version
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-951

#954 protractor upgraded for saucelabs
  package.json
  test/e2e/config/crossbrowser.conf.js
  yarn.lock
Labels: ns:jui-webapp-pr-954

#953 testing adding redis
  infrastructure/main.tf
Labels: ns:jui-webapp-pr-953

#956 Chore/disable tests to get build up
  infrastructure/main.tf
  package.json
  test/e2e/config/smoke.conf.js
Labels: ns:jui-webapp-pr-956

#959 update jui
  README.md
  infrastructure/main.tf
Labels: ns:jui-webapp-pr-959

#962 Revert "Revert "Merge remote-tracking branch 'origin/master'" (#961)"
  Jenkinsfile_nightly
  api/controllers/case-list/index.spec.ts
  api/controllers/case-list/index.ts
  api/controllers/decisions/cohDecisions.spec.ts
  api/controllers/decisions/cohDecisions.ts
  api/controllers/decisions/sscs/templates/benefit/setAwardDates.ts
  api/controllers/decisions/states.spec.ts
  api/controllers/decisions/states.ts
  api/controllers/documents/index.spec.ts
  api/controllers/documents/index.ts
  api/index.ts
  api/lib/middleware/accessControlAllowOriginHeaders.spec.ts
  api/lib/middleware/accessControlAllowOriginHeaders.ts
  api/services/bar.spec.ts
  api/services/bar.ts
  api/services/cohQA.ts
  package.json
  src/app/domain/components/questions/create/create.component.ts
  src/app/domain/components/questions/edit/edit.component.ts
  src/app/domain/services/question.service.spec.ts
  src/app/domain/services/question.service.ts
  src/app/routing/pages/decisions/check-decision/check-decision.component.html
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.spec.ts
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.ts
  src/app/routing/pages/hearings/hearing-confirmation/hearing-confirmation.component.html
  src/app/shared/components/question-list/question-list.component.html
  src/app/shared/services/validation.service.spec.ts
  src/app/shared/services/validation.service.ts
  test/e2e/config/conf.js
  test/e2e/config/crossbrowser.conf.js
  test/e2e/config/protractor.conf.js
  test/e2e/config/smoke.conf.js
  test/karma.conf.js
  yarn.lock
Labels: ns:jui-webapp-pr-962

#967 Chore/update encrypted file with judge users
  api/lib/config/refJudgeLookUp.crypt
Labels: ns:jui-webapp-pr-967
