Repository hmcts/rpa-jui-webapp, pull requests merged in 2019-01, with the labels that each got.

#452 Feature/update pv to set decision state on submit
  api/.prettierrc
  api/controllers/case-list/index.ts
  api/controllers/decisions/sscs/index.ts
  api/controllers/decisions/sscs/mapping.ts
  api/lib/stateEngine.ts
  api/services/ccd-store-api/ccd-store.ts
  api/services/coh.ts
  application.ts
Labels: ns:jui-webapp-pr-452

#439 Fix: RIUI- 1352 - fixing back link
  src/app/govuk/components/govuk-back-link/govuk-back-link.component.html
  src/app/govuk/components/govuk-back-link/govuk-back-link.component.ts
Labels: ns:jui-webapp-pr-439

#410 Jenkins parameterized update
  Jenkinsfile_parameterized
  infrastructure/main.tf
Labels: ns:jui-webapp-pr-410

#462 Validation bug fixed - RIUI957
  api/controllers/decisions/divorce/templates/financialremedymvp2/hearingDetails.ts
Labels: ns:jui-webapp-pr-462

#468 RIUI-732 page is done, RIUI-1113 bug fixed
  api/controllers/decisions/divorce/index.ts
  api/controllers/decisions/divorce/mapping.ts
  api/controllers/decisions/divorce/templates/divorce/create.ts
  api/controllers/decisions/divorce/templates/financialremedymvp2/check.ts
  api/controllers/decisions/divorce/templates/index.ts
  api/controllers/decisions/states.ts
  api/lib/stateEngine.ts
  src/app/routing/pages/decisions/check-decision/check-decision.component.html
  src/app/routing/pages/decisions/check-decision/check-decision.component.ts
  src/app/routing/pages/decisions/draft-consent-order/draft-consent-order.component.html
  src/app/routing/pages/decisions/draft-consent-order/draft-consent-order.component.scss
  src/app/routing/pages/decisions/draft-consent-order/draft-consent-order.component.spec.ts
  src/app/routing/pages/decisions/draft-consent-order/draft-consent-order.component.ts
  src/app/routing/pages/decisions/make-decision/make-decision.component.html
  src/app/routing/pages/decisions/make-decision/make-decision.component.scss
  src/app/routing/pages/decisions/make-decision/make-decision.component.spec.ts
  src/app/routing/pages/decisions/make-decision/make-decision.component.ts
  src/app/routing/routing.module.ts
Labels: ns:jui-webapp-pr-468

#480 disable sscs tests as judge details wiped off
  test/e2e/features/app/dashBoard.feature
  test/e2e/features/app/login.feature
Labels: ns:jui-webapp-pr-480

#469 Experimental Async await [DO NOT MERGE]
  api/controllers/auth/auth.spec.ts
  api/controllers/auth/index.ts
  api/controllers/case-list/index.ts
  api/controllers/case/index.ts
  api/controllers/documents/index.ts
  api/controllers/events/index.ts
  api/controllers/questions/index.ts
  api/index.ts
  api/lib/interceptors.ts
  api/lib/middleware/auth.ts
  api/lib/util.ts
  api/services/ccd-store-api/ccd-store.spec.ts
  api/services/ccd-store-api/ccd-store.ts
  api/services/coh-cor-api/coh-cor-api.spec.ts
  api/services/coh-cor-api/coh-cor-api.ts
  api/services/dm-store-api/dm-store-api.spec.ts
  api/services/dm-store-api/dm-store-api.ts
  api/services/idam-api/idam-api.spec.ts
  package-lock.json
  src/app/domain/components/header/header.component.ts
Labels: ns:jui-webapp-pr-469

#479 RIUI-738, RIUI-1114 divorce front end
  api/controllers/decisions/divorce/mapping.ts
  api/controllers/decisions/divorce/templates/divorce/checkYourAnswers.ts
  api/controllers/decisions/divorce/templates/divorce/costsOrder.ts
  api/controllers/decisions/divorce/templates/divorce/create.ts
  api/controllers/decisions/divorce/templates/divorce/provideReason.ts
  api/controllers/decisions/divorce/templates/index.ts
  api/controllers/decisions/sscs/templates/benefit/finalDecision.ts
  api/lib/stateEngine.ts
  src/app/shared/components/radiobutton/radiobutton.component.html
Labels: ns:jui-webapp-pr-479

#483 basic typing
  api/lib/models/index.ts
  api/services/ccd-store-api/ccd-store.ts
Labels: ns:jui-webapp-pr-483

#482 Change ordering
  api/controllers/decisions/sscs/mapping.ts
Labels: ns:jui-webapp-pr-482

#484 Divorce is partially done
  api/controllers/decisions/divorce/templates/divorce/checkYourAnswers.ts
  api/controllers/decisions/divorce/templates/divorce/costsOrder.ts
  api/controllers/decisions/divorce/templates/divorce/create.ts
  src/app/routing/routing.module.ts
Labels: ns:jui-webapp-pr-484

#485 Bug/riui 1379 empty event showing
  api/controllers/events/index.ts
  api/services/coh-cor-api/coh-cor-api.ts
Labels: ns:jui-webapp-pr-485

#492 enable reporting for functional tests and restricting build for prod …
  Jenkinsfile_CNP
Labels: ns:jui-webapp-pr-492

#488 Bug/fix expiry date issue
  api/controllers/questions/index.ts
Labels: ns:jui-webapp-pr-488

#486 Feature: rich text editor
  src/app/domain/components/questions/check/check.component.html
  src/app/domain/components/questions/create/create.component.html
  src/app/domain/components/questions/edit/edit.component.html
  src/app/domain/components/questions/view/view.component.html
  src/app/forms/components/text-editor/text-editor.component.html
  src/app/forms/components/text-editor/text-editor.component.spec.ts
  src/app/forms/components/text-editor/text-editor.component.ts
  src/app/forms/components/text-editor/textarea-custom/textarea-custom.component.html
  src/app/forms/components/text-editor/textarea-custom/textarea-custom.component.spec.ts
  src/app/forms/components/text-editor/textarea-custom/textarea-custom.component.ts
  src/app/forms/components/textarea/textarea.component.html
  src/app/forms/components/textarea/textarea.component.spec.ts
  src/app/forms/components/textarea/textarea.component.ts
  src/app/forms/forms.module.ts
Labels: ns:jui-webapp-pr-486

#501 Bug/events not pulling through
  api/controllers/events/index.ts
Labels: ns:jui-webapp-pr-501

#497 changing footer info
  src/app/shared/components/footer/footer.component.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: ns:jui-webapp-pr-497

#506 Test: Increased test coverage to 87%
  src/app/domain/case-viewer/components/document-panel/document-panel.component.spec.ts
  src/app/domain/case-viewer/components/document-panel/document-panel.component.ts
  src/app/routing/pages/decisions/check-decision/check-decision.component.spec.ts
  src/app/routing/pages/decisions/check-decision/check-decision.component.ts
  src/app/routing/pages/decisions/draft-consent-order/draft-consent-order.component.spec.ts
  src/app/routing/pages/decisions/make-decision/make-decision.component.spec.ts
  src/app/routing/pages/view-case/view-case.services.spec.ts
  src/app/shared/components/document/case-file-tree-list/case-file-tree-list.component.html
  src/app/shared/components/tabs/tabs.component.spec.ts
  src/app/shared/services/forms.service.spec.ts
Labels: ns:jui-webapp-pr-506

#507 sonar enabled
  sonar-project.properties
Labels: ns:jui-webapp-pr-507

#509 Feature/riui 1383 question sent and decision made are not reflected
  api/controllers/case-list/assignCase.ts
  api/controllers/case/index.ts
  api/controllers/events/index.ts
  api/index.ts
  api/lib/processors/case-state-model.ts
  api/lib/processors/case-state-util.ts
  api/lib/stack.ts
Labels: ns:jui-webapp-pr-509

#514 fixing sonar bugs
  src/app/shared/components/hmcts-em-viewer-ui/data/annotation-store.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/pdf-adapter.ts
  src/app/shared/services/validation.service.ts
Labels: ns:jui-webapp-pr-514

#513 Bug/fz accesibilty fixes
  api/controllers/decisions/divorce/templates/financialremedymvp2/hearingDetails.ts
  src/app/hmcts/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/routing/pages/hearings/root/root.component.html
Labels: ns:jui-webapp-pr-513

#519 fixing the cta aligment
  src/public/sass/jui/all.scss
Labels: ns:jui-webapp-pr-519

#524 filter on final decision
  api/lib/processors/case-state-model.ts
Labels: ns:jui-webapp-pr-524

#520 Em viewer test coverage
  src/app/shared/components/hmcts-em-viewer-ui/data/annotation-store.service.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/js-wrapper/pdf-annotate-wrapper.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/js-wrapper/pdf-wrapper.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/pdf-render.service.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/rotation-toolbar/rotation-factory.service.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/viewer-factory.service.ts
Labels: ns:jui-webapp-pr-520

#526 improved logging
  api/lib/interceptors.ts
Labels: ns:jui-webapp-pr-526

#522 Feature: Decree nisi and decree absolute dates are displayed in the Financial Remedy case summary
  api/controllers/case/index.ts
  api/controllers/case/templates/divorce/financialremedy.ts
  api/lib/processors/value-processor.ts
  api/tsconfig.json
Labels: ns:jui-webapp-pr-522

#525 Bug/fz final d list h riui 1414 riui 1415
  api/controllers/decisions/sscs/templates/benefit/setAwardDates.ts
  src/app/hmcts/components/hmcts-primary-navigation/hmcts-primary-navigation.component.html
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.html
Labels: ns:jui-webapp-pr-525

#521 Chore/riui 1324 security fixes
  api/lib/middleware/helmet.ts
  api/tsconfig.json
  application.ts
  config/environments/demo.config.js
  config/environments/demo.config.ts
  config/environments/prod.config.js
  config/environments/prod.config.ts
  package-lock.json
  package.json
  src/app/auth/auth.module.ts
  src/app/auth/cache-inteceptor.ts
  src/index.html
  yarn.lock
Labels: ns:jui-webapp-pr-521

#540 fixing wrong case number displayed on confirmation page
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.html
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.ts
Labels: ns:jui-webapp-pr-540

#543 new document management api
  api/controllers/case/index.ts
  api/controllers/documents/index.ts
  api/index.ts
  api/services/DMStore.ts
  api/services/dm-store-api/dm-store-api.spec.ts
  api/services/dm-store-api/dm-store-api.ts
  application.ts
Labels: ns:jui-webapp-pr-543

#541 Bug: removed back link on confirmation page
  src/app/routing/pages/hearings/root/root.component.html
  src/app/routing/pages/hearings/root/root.component.spec.ts
  src/app/routing/pages/hearings/root/root.component.ts
Labels: ns:jui-webapp-pr-541

#545 enable logging
  config/environments/aat.config.ts
  config/environments/demo.config.ts
  config/environments/preview.config.ts
Labels: ns:jui-webapp-pr-545

#546 removed helmet for debugging purposes
  application.ts
  src/app/auth/auth.module.ts
  src/app/auth/cache-inteceptor.ts
Labels: ns:jui-webapp-pr-546

#551 added helmet back in but disabled all defaults and required libraries
  application.ts
Labels: ns:jui-webapp-pr-551

#542 EM-965: adjust annotation coordinates to account for rotation
  src/public/javascripts/pdf-annotate.js
Labels: ns:jui-webapp-pr-542

#554 caselist tidy up and added filtering on roles for panel members
  api/controllers/case-list/index.ts
  api/lib/config/cohConstants.ts
  api/lib/config/refCaselistCols.ts
  api/lib/config/refCaselistFilters.ts
  api/lib/config/refCaselistRoleFilters.ts
  api/lib/filters.ts
  api/services/ccd-store-api/ccd-store.ts
  api/services/coh.ts
  api/services/idam-api/idam-api.ts
  package-lock.json
Labels: ns:jui-webapp-pr-554

#555 removed all helmet references to enable builds passing on master
  api/lib/middleware/helmet.ts
  application.ts
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-555

#558 RIUI-1267 Radio button conditional validation is complete.
  api/controllers/decisions/sscs/templates/benefit/setAwardDates.ts
  api/lib/stateEngine.ts
  src/app/shared/services/validation.service.ts
Labels: ns:jui-webapp-pr-558

#559 Chore/riui 1329 remove cached responses
  api/lib/middleware/nocache.ts
  application.ts
Labels: ns:jui-webapp-pr-559

#560 Chore/riui 1334 information disclosure in response
  api/lib/middleware/hide-powered-by.ts
  application.ts
Labels: ns:jui-webapp-pr-560

#561 Refactor/riui 1324 security headers
  api/lib/middleware/index.ts
  api/lib/middleware/security-headers.ts
  application.ts
Labels: ns:jui-webapp-pr-561

#565 Bug/riui 1428 pdfs not appearing
  api/controllers/case/index.ts
  api/index.ts
  api/lib/models/index.ts
Labels: ns:jui-webapp-pr-565

#567 Bug/coh create hearing bug
  api/controllers/case/index.ts
  api/controllers/events/index.ts
  api/lib/interceptors.ts
  api/services/coh-cor-api/coh-cor-api.ts
Labels: ns:jui-webapp-pr-567

#568 panel member filtering
  api/controllers/case-list/index.ts
  api/controllers/case/index.ts
  api/controllers/case/templates/sscs/benefit.ts
  api/lib/config/refCaselistRoleFilters.ts
  api/lib/config/refJudgeLookUp.ts
  api/lib/filters.ts
  api/services/idam-api/idam-api.ts
Labels: ns:jui-webapp-pr-568

#569 Testing change in cnp jenkins file
  Jenkinsfile_CNP
Labels: ns:jui-webapp-pr-569

#571 Endingpipelinetest
  Jenkinsfile_CNP
Labels: ns:jui-webapp-pr-571

#574 RIUI-1417 fixed
  api/controllers/decisions/sscs/templates/benefit/checkFinalDecision.ts
Labels: ns:jui-webapp-pr-574

#575 RIUI-1434 fixed
  src/app/routing/pages/hearings/create-hearing/create-hearing.component.html
  src/app/routing/pages/hearings/create-hearing/create-hearing.component.ts
Labels: ns:jui-webapp-pr-575

#576 trust proxy
  application.ts
Labels: ns:jui-webapp-pr-576

#572 encrypted data file and decrypt functionality
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  api/controllers/case/index.ts
  api/controllers/case/templates/sscs/benefit.ts
  api/controllers/decisions/divorce/index.ts
  api/lib/config/refJudgeLookUp.crypt
  api/lib/config/refJudgeLookUp.ts
  api/lib/encryption.ts
  api/package-lock.json
  api/package.json
  infrastructure/main.tf
  kubernetes/deployment.template.yaml
  package.json
  server.ts
Labels: ns:jui-webapp-pr-572

#580 fixed typo
  api/controllers/decisions/config_examples.MD
  api/controllers/decisions/divorce/templates/financialremedymvp2/rejectReasons.ts
Labels: ns:jui-webapp-pr-580

#581 Remove typo when saving the changes
  src/public/javascripts/pdf.worker.js
Labels: ns:jui-webapp-pr-581

#585 Date validation complete
  api/controllers/decisions/sscs/templates/benefit/setAwardDates.ts
  src/app/routing/pages/decisions/draft-consent-order/draft-consent-order.component.spec.ts
  src/app/routing/pages/decisions/make-decision/make-decision.component.spec.ts
  src/app/shared/components/date/date.component.html
  src/app/shared/services/forms.service.spec.ts
  src/app/shared/services/validation.service.spec.ts
  src/app/shared/services/validation.service.ts
  src/app/shared/shared.module.ts
Labels: ns:jui-webapp-pr-585

#582 Configuring helm charts
  Jenkinsfile_CNP
  application.ts
  charts/jui-webapp/Chart.yaml
  charts/jui-webapp/requirements.yaml
  charts/jui-webapp/values.aat.template.yaml
  charts/jui-webapp/values.template.yaml
  infrastructure/main.tf
  kubernetes/config.aat.yaml
  kubernetes/config.saat.yaml
  kubernetes/deployment.template.yaml
Labels: ns:jui-webapp-pr-582

#588 Feature/app insights logging
  README.md
  api/controllers/auth/index.ts
  api/controllers/case/index.ts
  api/controllers/decisions/divorce/index.ts
  api/controllers/decisions/sscs/index.ts
  api/controllers/decisions/states.ts
  api/lib/appInsights.ts
  api/lib/encryption.ts
  api/lib/interceptors.ts
  api/lib/log4jui.ts
  api/lib/models/index.ts
  api/lib/stack.ts
  api/lib/stateEngine.ts
  api/lib/util.ts
  api/services/DMStore.ts
  api/services/ccd-store-api/ccd-store.ts
  api/services/coh.ts
  application.ts
  config/index.ts
  package.json
Labels: ns:jui-webapp-pr-588
