Repository hmcts/rpa-jui-webapp, pull requests merged in 2019-03, with the labels that each got.

#760 document-store-service unit tests coverage increased up to 77%
  src/app/govuk/components/govuk-table/govuk-table.component.html
  src/app/shared/components/data-list/data-list.component.html
  src/app/shared/components/tabs/tabs.component.spec.ts
  src/app/shared/services/documentStore/document-store-service.service.spec.ts
  src/app/shared/services/documentStore/document-store.service.ts
Labels: ns:jui-webapp-pr-760

#766 tidy up security headers
  api/index.ts
  api/lib/middleware/frameguard.ts
  api/lib/middleware/hide-powered-by.ts
  api/lib/middleware/index.ts
  api/lib/middleware/nocache.ts
  api/lib/middleware/security-headers.ts
  api/lib/middleware/securityHeaders.ts
  api/lib/middleware/serviceToken.ts
  application.ts
Labels: ns:jui-webapp-pr-766

#578 Fix/em 1090 fix ui for rotation
  src/app/domain/case-viewer/components/case-viewer/case-viewer.component.html
  src/app/routing/pages/view-case/view-case.component.html
  src/app/shared/components/case-actions/case-actions.component.html
  src/app/shared/components/document/case-file-tool-bar/case-file-tool-bar.component.html
  src/app/shared/components/document/case-file-tool-bar/case-file-tool-bar.component.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/pdf-render.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/annotation-pdf-viewer.component.scss
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/comments/comments.component.scss
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/rotation-toolbar/rotation-factory.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/rotation-toolbar/rotation.component.html
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/rotation-toolbar/rotation.component.scss
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/rotation-toolbar/rotation.component.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/rotation-toolbar/rotation.component.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/rotation-toolbar/rotation.service.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/rotation-toolbar/rotation.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/image-viewer/image-viewer.component.html
  src/app/shared/components/hmcts-em-viewer-ui/viewers/image-viewer/image-viewer.component.scss
  src/app/shared/components/hmcts-em-viewer-ui/viewers/image-viewer/image-viewer.component.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/image-viewer/image-viewer.component.ts
  src/public/components/casefile/_casefile.scss
  src/public/javascripts/pdf-annotate.js
  src/public/sass/annotation-ui-theme.scss
Labels: Awaiting Final Fix, ns:jui-webapp-pr-578

#771 Updating node version in azure
  infrastructure/main.tf
Labels: ns:jui-webapp-pr-771

#770 Fix/rotation button disable
  README.md
  src/app/shared/components/document/case-file-tool-bar/case-file-tool-bar.component.html
  src/app/shared/components/document/case-file-tool-bar/case-file-tool-bar.component.ts
Labels: ns:jui-webapp-pr-770

#774 Updating package lock file
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-774

#778 Updating package lock files and infra main
  infrastructure/main.tf
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-778

#763 RIUI-1520 fixed
  package-lock.json
  src/app/domain/components/casebar/casebar.component.html
  src/app/domain/components/casebar/casebar.component.spec.ts
  src/app/domain/components/casebar/casebar.component.ts
  src/app/domain/services/case.service.ts
  src/app/domain/services/exchange.service.spec.ts
  src/app/domain/services/exchange.service.ts
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.html
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.spec.ts
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.ts
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.model.ts
  src/app/routing/pages/decisions/make-decision/make-decision.component.ts
  yarn.lock
Labels: ns:jui-webapp-pr-763

#762 changing ase name for sprod test
  infrastructure/main.tf
Labels: ns:jui-webapp-pr-762

#785 chore/improve ordering of login
  api/index.ts
Labels: ns:jui-webapp-pr-785

#782 Test/increasing line coverage
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/rotation-toolbar/rotation.component.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/rotation-toolbar/rotation.service.ts
Labels: ns:jui-webapp-pr-782

#781 Feature/question ordinal
  api/controllers/questions/index.spec.ts
  api/controllers/questions/index.ts
Labels: ns:jui-webapp-pr-781

#783 fixed
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.spec.ts
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.ts
Labels: ns:jui-webapp-pr-783

#788 changed saat and spreview idam endpoints
  config/environments/saat.config.ts
  config/environments/spreview.config.ts
Labels: ns:jui-webapp-pr-788

#758 Chore/remove old request object from project - Risky - NO NOT MERGE (for now)
  api/controllers/documents/index.ts
  api/index.ts
  api/lib/request/mockRequest.ts
  api/lib/request/proxy.ts
  api/lib/request/request.ts
  api/lib/request/uploadFileFormData.ts
  api/services/DMStore.ts
  api/services/draftStore.ts
  api/services/em-npa-api/em-npa-api.ts
  api/services/emAnno.ts
  api/services/emNpa.ts
  package-lock.json
  package.json
  test/integration/tests/utils/generateAPI.js
Labels: ns:jui-webapp-pr-758

#787 Totally remove Upload components, and view from ng.
  src/app/domain/components/upload/upload.component.html
  src/app/domain/components/upload/upload.component.scss
  src/app/domain/components/upload/upload.component.spec.ts
  src/app/domain/components/upload/upload.component.ts
  src/app/domain/domain.module.ts
  src/app/routing/routing.module.ts
Labels: ns:jui-webapp-pr-787

#780 Hearing submit screen fixed RIUI-1520
  src/app/routing/pages/hearings/hearing-confirmation/hearing-confirmation.component.html
  src/app/routing/pages/hearings/hearing-confirmation/hearing-confirmation.component.ts
Labels: ns:jui-webapp-pr-780

#793 Chore/remove old request object from project
  api/controllers/documents/index.ts
  api/index.ts
  api/lib/request/mockRequest.ts
  api/lib/request/proxy.ts
  api/lib/request/request.ts
  api/lib/request/uploadFileFormData.ts
  api/services/DMStore.ts
  api/services/draftStore.ts
  api/services/em-npa-api/em-npa-api.ts
  api/services/emAnno.ts
  api/services/emNpa.ts
  package-lock.json
  package.json
  test/integration/tests/utils/generateAPI.js
Labels: ns:jui-webapp-pr-793

#796 Fixed
  src/app/shared/components/document/case-file/case-file.component.html
Labels: ns:jui-webapp-pr-796

#797 chore/ignore coh error for non -sscs cases
  api/controllers/case-list/index.ts
  api/services/ccd-store-api/ccd-store.ts
Labels: ns:jui-webapp-pr-797

#748 Chore/update build angular
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-748

#801 Chore/ignore coh error for non sscs cases
  test/e2e/config/conf.js
  test/e2e/features/app/login.feature
Labels: ns:jui-webapp-pr-801

#806 Fixed
  api/controllers/case-list/index.spec.ts
Labels: ns:jui-webapp-pr-806

#809 better session expiry handling
  api/lib/middleware/auth.ts
  api/package.json
  api/services/ccd-store-api/ccd-store.ts
Labels: ns:jui-webapp-pr-809

#813 add test condition for toggling false to true to false
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/rotation-toolbar/rotation.service.spec.ts
Labels: ns:jui-webapp-pr-813

#812 adding modules for fix deployment to kudu
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-812

#816 Revert "adding modules for fix deployment to kudu"
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-816

#814 Chore/riui 1537 ensure user id and session id are present in logs
  api/controllers/auth/index.spec.ts
  api/controllers/auth/index.ts
  api/index.ts
  api/lib/log4jui.spec.ts
  api/lib/log4jui.ts
  api/lib/middleware/auth.ts
  api/lib/middleware/responseRequest.ts
  api/lib/models/index.ts
  api/package.json
  config/application.config.ts
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-814

#820 done
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.html
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.spec.ts
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.ts
Labels: ns:jui-webapp-pr-820

#819 Testing kudu deployments DON'T MERGE
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-819

#821 Chore/test for requestresponse
  api/lib/log4jui.spec.ts
  api/lib/log4jui.ts
  api/lib/middleware/responseRequest.spec.ts
  api/package.json
Labels: ns:jui-webapp-pr-821

#823 unit tests
  api/controllers/case/index.spec.ts
  api/controllers/case/index.ts
  api/lib/log4jui.ts
Labels: ns:jui-webapp-pr-823

#826 Chore/issue with restarting node while being logged in
  api/lib/log4jui.ts
Labels: ns:jui-webapp-pr-826

#818 Chore/riui 1539 app logging tidy
  api/controllers/case-list/index.ts
  api/lib/interceptors.spec.ts
  api/lib/log4jui.spec.ts
  api/lib/log4jui.ts
  api/lib/models/index.ts
  config/application.config.ts
Labels: ns:jui-webapp-pr-818

#828 Feature/riui 1133 citizen and caseworker account is able to login
  api/lib/middleware/auth.spec.ts
  api/lib/middleware/auth.ts
  config/application.config.ts
Labels: ns:jui-webapp-pr-828

#829 Adding sandbox config
  config/environments/sandbox.config.ts
  config/index.ts
  infrastructure/sandbox.tfvars
Labels: ns:jui-webapp-pr-829

#772 Fix/em 1255 highlight blurs when selected
  src/public/javascripts/pdf-annotate.js
  src/public/sass/annotation-ui-theme.scss
Labels: ns:jui-webapp-pr-772

#825 Feature/error visual
  api/controllers/case-list/index.spec.ts
  api/controllers/case-list/index.ts
  api/controllers/questions/index.spec.ts
  api/controllers/questions/index.ts
  src/app/domain/components/search-result/search-result.component.html
  src/app/domain/components/search-result/search-result.component.scss
  src/app/domain/components/search-result/search-result.component.spec.ts
  src/app/domain/components/search-result/search-result.component.ts
  src/app/domain/services/case.service.spec.ts
  src/app/domain/services/case.service.ts
  src/app/shared/services/error-formatting.service.spec.ts
  src/app/shared/services/error-formatting.service.ts
Labels: ns:jui-webapp-pr-825

#831 unit tests fixed
  src/app/config.service.spec.ts
  src/app/config.service.ts
  src/app/domain/services/decision.service.spec.ts
  src/app/routing/pages/hearings/hearing-confirmation/hearing-confirmation.component.spec.ts
Labels: ns:jui-webapp-pr-831

#832 Bug/riui 1546 annotations broken on jui aat
  api/lib/util.ts
  api/services/emAnno.ts
Labels: ns:jui-webapp-pr-832

#833 More unit tests
  src/app/domain/components/casebar/casebar.component.spec.ts
  src/app/domain/services/exchange.service.ts
Labels: ns:jui-webapp-pr-833

#830 Feat: Introduce HmctsrolesLibModule from @hmcts/hmctsroles-lib
  package-lock.json
  package.json
  src/app/auth/auth.service.ts
  src/app/domain/case-viewer/components/document-panel/document-panel.component.html
  src/app/domain/case-viewer/components/document-panel/document-panel.component.spec.ts
  src/app/domain/case-viewer/components/document-panel/document-panel.component.ts
  src/app/domain/case-viewer/components/parties-panel/parties-panel.component.html
  src/app/domain/case-viewer/components/parties-panel/parties-panel.component.spec.ts
  src/app/domain/case-viewer/components/parties-panel/parties-panel.component.ts
  src/app/domain/case-viewer/components/questions-panel/questions-panel.component.html
  src/app/domain/case-viewer/components/questions-panel/questions-panel.component.spec.ts
  src/app/domain/case-viewer/components/questions-panel/questions-panel.component.ts
  src/app/domain/case-viewer/components/summary-panel/summary-panel.component.html
  src/app/domain/case-viewer/components/summary-panel/summary-panel.component.spec.ts
  src/app/domain/case-viewer/components/summary-panel/summary-panel.component.ts
  src/app/domain/case-viewer/components/timeline-panel/timeline-panel.component.html
  src/app/domain/case-viewer/components/timeline-panel/timeline-panel.component.spec.ts
  src/app/domain/case-viewer/components/timeline-panel/timeline-panel.component.ts
  src/app/domain/domain.module.ts
  src/app/routing/pages/hearings/create-hearing/create-hearing.component.spec.ts
  src/app/shared/components/case-actions/case-actions.component.html
  src/app/shared/components/case-actions/case-actions.component.spec.ts
  src/app/shared/components/case-actions/case-actions.component.ts
  src/app/shared/components/question/question.component.html
  src/app/shared/components/question/question.component.ts
  src/app/shared/shared.module.ts
  yarn.lock
Labels: ns:jui-webapp-pr-830

#839 Chore/auth unit tests
  api/lib/middleware/auth.spec.ts
  api/lib/middleware/auth.ts
  package-lock.json
  package.json
  support/old-tests/api/bar-api.spec.ts
  support/old-tests/api/case-list.spec.ts
  support/old-tests/api/case.spec.ts
  support/old-tests/api/ccd-def-api.spec.ts
  support/old-tests/api/ccd-store.spec.ts
  support/old-tests/api/coh-cor-api.spec.ts
  support/old-tests/api/coh.spec.ts
  support/old-tests/api/draft-store-api.spec.ts
  support/old-tests/api/em-anno-api.spec.ts
  support/old-tests/api/em-npa-api.spec.ts
  support/old-tests/api/fee-api.spec.ts
  support/old-tests/api/idam-api.spec.ts
  support/old-tests/api/pay-api.spec.ts
  support/old-tests/api/service-auth-provider-api.spec.ts
  yarn.lock
Labels: ns:jui-webapp-pr-839

#843 adding test for user roles service
  src/app/auth/auth.service.spec.ts
Labels: ns:jui-webapp-pr-843

#849 app.component unit tests fix
  src/app/app.component.spec.ts
  src/app/app.component.ts
Labels: ns:jui-webapp-pr-849

#852 Chore/em anno tests
  api/lib/middleware/auth.spec.ts
  api/services/emAnno.spec.ts
  api/services/emAnno.ts
Labels: ns:jui-webapp-pr-852

#856 case.service.ts unt test improved
  src/app/domain/services/case.service.spec.ts
  src/app/domain/services/case.service.ts
  src/app/routing/pages/decisions/check-decision/check-decision.component.spec.ts
Labels: ns:jui-webapp-pr-856

#857 Feature/dm store unit tests
  api/services/DMStore.spec.ts
Labels: ns:jui-webapp-pr-857

#861 Idam testing
  api/controllers/auth/index.spec.ts
  api/controllers/auth/index.ts
  api/controllers/case-list/assignCase.ts
  api/index.ts
  api/lib/interceptors.ts
  api/lib/middleware/auth.ts
  api/lib/middleware/responseRequest.ts
  api/services/idam.ts
  config/environments/local.config.ts
  support/bin/idam/idam-details.sh
Labels: ns:jui-webapp-pr-861

#863 chore/slightly better login handling
  api/controllers/auth/index.ts
Labels: ns:jui-webapp-pr-863

#864 More accurate coverage stats
  api/package.json
Labels: ns:jui-webapp-pr-864

#865 Bug/fz unit test fixes
  src/app/domain/components/casebar/casebar.component.spec.ts
  src/app/domain/services/case.service.spec.ts
  src/app/domain/services/exchange.service.spec.ts
  src/app/routing/pages/hearings/hearing-confirmation/hearing-confirmation.component.spec.ts
  src/app/routing/pages/hearings/hearing-confirmation/hearing-confirmation.component.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/rotation-toolbar/rotation.service.spec.ts
  src/app/shared/services/error-formatting.service.spec.ts
Labels: ns:jui-webapp-pr-865

#868 Chore/more reliable detail getting
  api/controllers/auth/index.ts
  api/services/idam.ts
Labels: ns:jui-webapp-pr-868

#870 Bug/auth roles for pdf rendering
  api/controllers/case/index.spec.ts
  api/controllers/case/index.ts
  api/lib/interceptors.ts
  api/lib/middleware/auth.ts
  api/services/idam.ts
Labels: ns:jui-webapp-pr-870

#871 Revert "More accurate coverage stats"
  api/package.json
Labels: ns:jui-webapp-pr-871

#875 Bug/stop logout not stopping execution
  api/lib/middleware/auth.ts
Labels: ns:jui-webapp-pr-875

#880 More accurate coverage stats
  api/package.json
Labels: ns:jui-webapp-pr-880

#879 Test/idam tests
  api/lib/interceptors.ts
  api/lib/middleware/auth.ts
  api/services/idam.spec.ts
Labels: ns:jui-webapp-pr-879

#882 ccdDef unit test.
  api/services/ccdDef.spec.ts
Labels: ns:jui-webapp-pr-882

#881 Feature/em npa
  api/services/emNpa.spec.ts
  api/services/emNpa.ts
Labels: ns:jui-webapp-pr-881
