Repository hmcts/rpa-jui-webapp, pull requests merged in 2019-08, with the labels that each got.

#1010 removed all references to state 'appealCreated'
  api/controllers/case-list/assignCase.ts
  api/controllers/case-list/case-list-spec-data.ts
  api/lib/case-list/case-list-helper.spec.ts
  api/lib/config/refCaselistFilters.ts
  api/lib/filters.spec.ts
  api/lib/interceptors.spec.ts
  api/lib/processors/case-state-util.spec.ts
  api/lib/processors/case-state-util.ts
  api/lib/processors/case-status-map.ts
  support/mock-server/mockserver.js
Labels: ns:jui-webapp-pr-1010

#1018 changed https to http for draft store API in all envs
  config/environments/demo.config.ts
  config/environments/prod.config.ts
  config/environments/saat.config.ts
  config/environments/sandbox.config.ts
  config/environments/spreview.config.ts
  config/environments/sprod.config.ts
Labels: ns:jui-webapp-pr-1018

#1023 Fix helm 2
  charts/jui-webapp/requirements.yaml
  charts/jui-webapp/values.template.yaml
Labels: ns:jui-webapp-pr-1023

#1021 removed incorrect conditional checks
  src/app/shared/services/validation.service.ts
Labels: ns:jui-webapp-pr-1021

#1025 adjusting jenk CNP
  Jenkinsfile_CNP
  charts/jui-webapp/values.aat.template.yaml
  charts/jui-webapp/values.preview.template.yaml
  charts/jui-webapp/values.yaml
Labels: ns:jui-webapp-pr-1025
