Repository hmcts/rpa-jui-webapp, pull requests merged in 2019-06, with the labels that each got.

#970 Change prod sidam endpoints to correct urls
  config/environments/prod.config.ts
Labels: ns:jui-webapp-pr-970

#971 disable tests
  test/e2e/config/conf.js
  test/e2e/config/smoke.conf.js
Labels: ns:jui-webapp-pr-971

#973 chore/remove appinights disable
  api/lib/appInsights.ts
Labels: ns:jui-webapp-pr-973

#974 enable redis on tf
  infrastructure/main.tf
Labels: ns:jui-webapp-pr-974

#977 use redis for session store
  application.ts
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-977

#982 Feature/enable redis use
  application.ts
Labels: ns:jui-webapp-pr-982

#985 check decision text
  src/app/routing/pages/decisions/check-decision/check-decision.component.html
Labels: ns:jui-webapp-pr-985
