Repository hmcts/rpa-jui-webapp, pull requests merged in 2019-09, with the labels that each got.

#1027 updated templates to reflect new content changes
  api/controllers/decisions/sscs/templates/benefit/check.ts
  api/controllers/decisions/sscs/templates/benefit/checkTribunal.ts
  api/controllers/decisions/sscs/templates/benefit/planningJourneys.ts
Labels: ns:jui-webapp-pr-1027

#1029 Feature/riui 1843 content issue for pv
  api/controllers/decisions/sscs/templates/benefit/check.ts
Labels: ns:jui-webapp-pr-1029

#1030 Feature/riui 1839 show loading to improve ux
  angular.json
  application.ts
  package-lock.json
  package.json
  sonar-project.properties
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/loader.interceptor.service.mock.ts
  src/app/loader.interceptor.spec.ts
  src/app/loader.interceptor.ts
  src/app/loader.service.spec.ts
  src/app/loader.service.ts
  src/app/shared/components/table/table.component.scss
  src/index.html
  src/styles.scss
  src/tsconfig.spec.json
  src/wallabyTest.ts
  wallaby.js
  yarn.lock
Labels: ns:jui-webapp-pr-1030

#1031 added tls param back in as fails in prod
  application.ts
Labels: ns:jui-webapp-pr-1031

#1033 Feature/riui 1833 Second test.
  sonar-project.properties
  src/app/routing/pages/page-not-found/page-not-found.component.html
  src/app/routing/pages/page-not-found/page-not-found.component.scss
  src/app/routing/pages/page-not-found/page-not-found.component.spec.ts
  src/app/routing/pages/page-not-found/page-not-found.component.ts
  src/app/routing/routing.module.ts
Labels: ns:jui-webapp-pr-1033

#1026 Feature/pagination with master branch
  api/controllers/case-list/assignCase.ts
  api/controllers/case-list/index.spec.ts
  api/controllers/case-list/index.ts
  api/lib/filters.ts
  api/lib/interceptors.ts
  api/lib/pagination.spec.ts
  api/lib/pagination.ts
  api/services/ccd-store-api/ccd-store.spec.ts
  api/services/ccd-store-api/ccd-store.ts
  src/app/domain/components/search-result/search-result.component.html
  src/app/domain/components/search-result/search-result.component.scss
  src/app/domain/components/search-result/search-result.component.spec.ts
  src/app/domain/components/search-result/search-result.component.ts
  src/app/domain/services/case.service.spec.ts
  src/app/domain/services/case.service.ts
Labels: ns:jui-webapp-pr-1026

#1037 changed s2s url protocol
  config/environments/aat.config.ts
  config/environments/demo.config.ts
  config/environments/local.config.ts
  config/environments/mock.config.ts
  config/environments/preview.config.ts
  config/environments/prod.config.ts
  config/environments/saat.config.ts
  config/environments/sandbox.config.ts
  config/environments/spreview.config.ts
  config/environments/sprod.config.ts
Labels: ns:jui-webapp-pr-1037

#1038 updated redis-cache module source in terraform
  infrastructure/main.tf
Labels: ns:jui-webapp-pr-1038
