Repository hmcts/rpa-jui-webapp, pull requests merged in 2019-02, with the labels that each got.

#591 Disable node coverage for now
  api/package.json
  package.json
  support/old-tests/api/bar-api.spec.ts
  support/old-tests/api/case-list.spec.ts
  support/old-tests/api/case.spec.ts
  support/old-tests/api/ccd-def-api.spec.ts
  support/old-tests/api/ccd-store.spec.ts
  support/old-tests/api/coh-cor-api.spec.ts
  support/old-tests/api/coh.spec.ts
  support/old-tests/api/controllers/case-creation/case-creation.spec.ts
  support/old-tests/api/controllers/case-list/case-list-spec-data.ts
  support/old-tests/api/controllers/case-list/case-list.spec.ts
  support/old-tests/api/controllers/case/case.spec.ts
  support/old-tests/api/controllers/documents/documents.spec.ts
  support/old-tests/api/controllers/events/event.spec.ts
  support/old-tests/api/controllers/questions/question.spec.ts
  support/old-tests/api/draft-store-api.spec.ts
  support/old-tests/api/em-anno-api.spec.ts
  support/old-tests/api/em-npa-api.spec.ts
  support/old-tests/api/fee-api.spec.ts
  support/old-tests/api/idam-api.spec.ts
  support/old-tests/api/lib/middleware/auth.spec.ts
  support/old-tests/api/lib/middleware/service-token.spec.ts
  support/old-tests/api/lib/processors/case-state-model.spec.ts
  support/old-tests/api/lib/processors/case-state-util.spec.ts
  support/old-tests/api/lib/processors/case-status-processor.spec.ts
  support/old-tests/api/lib/processors/document-processor.spec.ts
  support/old-tests/api/lib/processors/value-processor.spec.ts
  support/old-tests/api/pay-api.spec.ts
  support/old-tests/api/service-auth-provider-api.spec.ts
  support/old-tests/api/services/bar-api.spec.ts
  support/old-tests/api/services/ccd-def-api.spec.ts
  support/old-tests/api/services/ccd-store.spec.ts
  support/old-tests/api/services/coh-cor-api.spec.ts
  support/old-tests/api/services/dm-store-api.spec.ts
  support/old-tests/api/services/draft-store-api.spec.ts
  support/old-tests/api/services/em-anno-api.spec.ts
  support/old-tests/api/services/em-npa-api.spec.ts
  support/old-tests/api/services/fee-api.spec.ts
  support/old-tests/api/services/idam-api.spec.ts
  support/old-tests/api/services/pay-api.spec.ts
  support/old-tests/api/services/service-auth-provider-api.spec.ts
Labels: ns:jui-webapp-pr-591

#583 Feature/upload item continue 3
  api/controllers/documents/index.ts
  api/index.ts
  api/lib/config/errorConstants.ts
  api/lib/models/documents.ts
  api/lib/request/request.ts
  api/lib/request/uploadFileFormData.ts
  api/services/DMStore.ts
  api/services/ccd-store-api/ccd-store-payloads.ts
  api/services/ccd-store-api/ccd-store.ts
  src/app/domain/case-viewer/components/document-panel/document-panel.component.html
  src/app/domain/components/upload/upload.component.html
  src/app/domain/components/upload/upload.component.scss
  src/app/domain/components/upload/upload.component.spec.ts
  src/app/domain/components/upload/upload.component.ts
  src/app/domain/domain.module.ts
  src/app/routing/routing.module.ts
  src/app/shared/components/case-actions/case-actions.component.html
  src/app/shared/components/case-actions/case-actions.component.spec.ts
  src/app/shared/components/case-actions/case-actions.component.ts
  src/app/shared/services/documentStore/document-store.service.ts
  support/services/ccd-store-api/ccd-store-payloads.ts
Labels: ns:jui-webapp-pr-583

#596 Header links not linking to the right error message. Fixed (RIUI-1416)
  api/controllers/decisions/divorce/templates/divorce/create.ts
  api/controllers/decisions/divorce/templates/divorce/provideReason.ts
  api/controllers/decisions/divorce/templates/financialremedymvp2/create.ts
  api/controllers/decisions/divorce/templates/financialremedymvp2/hearingDetails.ts
  api/controllers/decisions/divorce/templates/financialremedymvp2/notesForCourtAdministrator.ts
  api/controllers/decisions/divorce/templates/financialremedymvp2/rejectReasons.ts
  api/controllers/decisions/sscs/templates/benefit/budgetingDecisions.ts
  api/controllers/decisions/sscs/templates/benefit/check.ts
  api/controllers/decisions/sscs/templates/benefit/communicatingVerbally.ts
  api/controllers/decisions/sscs/templates/benefit/create.ts
  api/controllers/decisions/sscs/templates/benefit/dressingUndressing.ts
  api/controllers/decisions/sscs/templates/benefit/engagingFace.ts
  api/controllers/decisions/sscs/templates/benefit/finalDecision.ts
  api/controllers/decisions/sscs/templates/benefit/managingTherapy.ts
  api/controllers/decisions/sscs/templates/benefit/managingToilet.ts
  api/controllers/decisions/sscs/templates/benefit/movingAround.ts
  api/controllers/decisions/sscs/templates/benefit/planningJourneys.ts
  api/controllers/decisions/sscs/templates/benefit/preliminaryAdvanced.ts
  api/controllers/decisions/sscs/templates/benefit/preparingFood.ts
  api/controllers/decisions/sscs/templates/benefit/readingSigns.ts
  api/controllers/decisions/sscs/templates/benefit/scores.ts
  api/controllers/decisions/sscs/templates/benefit/setAwardDates.ts
  api/controllers/decisions/sscs/templates/benefit/takingNutrition.ts
  api/controllers/decisions/sscs/templates/benefit/washingBathing.ts
  src/app/shared/components/validation-error-formcontrol/validation-error-formcontrol.component.html
  src/app/shared/components/validation-error-formgroup/validation-error-formgroup.component.html
  src/app/shared/components/validation-header/validation-header.component.html
Labels: ns:jui-webapp-pr-596

#599 Case List columns need to wrap better RIUI-932 fixed
  src/app/shared/components/table/table.component.scss
Labels: ns:jui-webapp-pr-599

#600 restructure of case list
  api/controllers/case-list/index.ts
  api/controllers/decisions/sscs/mapping.ts
Labels: ns:jui-webapp-pr-600

#593 Add env config for additional hostname
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:jui-webapp-pr-593

#607 Update config.service.ts
  src/app/config.service.ts
Labels: ns:jui-webapp-pr-607

#609 force https for jui demo
  src/app/config.service.ts
Labels: ns:jui-webapp-pr-609

#594 Node unit tests coverage: to 34.14%
  api/controllers/auth/index.spec.ts
  api/lib/stack.spec.ts
  api/lib/stateEngine.spec.ts
  api/lib/util.spec.ts
Labels: ns:jui-webapp-pr-594

#603 RIUI-1228 fixed
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.html
Labels: ns:jui-webapp-pr-603

#608 Removing the upload button.
  src/app/domain/case-viewer/components/document-panel/document-panel.component.html
Labels: ns:jui-webapp-pr-608

#611 Update config.service.ts
  src/app/config.service.ts
Labels: ns:jui-webapp-pr-611

#613 Bug/fix pdf rendering
  api/controllers/documents/index.ts
  api/index.ts
  api/services/DMStore.ts
Labels: ns:jui-webapp-pr-613

#612 Chore/master with bw test 2
  api/lib/filters.spec.ts
  api/lib/interceptors.spec.ts
  api/lib/store/store.spec.ts
  api/lib/utilities/headerUtilities.spec.ts
  api/test/mocha.opts
Labels: ns:jui-webapp-pr-612

#606 RIUI-1454 fixed
  src/app/shared/components/question/question.component.html
Labels: ns:jui-webapp-pr-606

#618 Bug/fix logging categories
  api/lib/log4jui.ts
  config/environments/demo.config.ts
Labels: ns:jui-webapp-pr-618

#626 1228 fixed Y-y
  src/app/routing/pages/decisions/decision-confirmation/decision-confirmation.component.html
Labels: ns:jui-webapp-pr-626

#625 Release/jui 1.0.0 bug fix DO NOT MERGE
  application.ts
  config/index.ts
  src/app/config.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/pdf-render.service.ts
Labels: ns:jui-webapp-pr-625

#635 Bug/riui 1488 jui sscs cases not showing
  api/lib/processors/case-state-model.ts
Labels: ns:jui-webapp-pr-635

#636 Test/hard coded https
  src/app/config.service.ts
Labels: ns:jui-webapp-pr-636

#637 Feature/remove hardcoded http after none fix of bug confirmed
  src/app/config.service.ts
Labels: ns:jui-webapp-pr-637

#638 Feature/riui 1279 productionize app error reporting
  api/index.ts
  api/lib/errorStack.ts
  api/lib/interceptors.ts
  api/lib/log4jui.ts
  api/lib/util.ts
  dev-server.ts
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-638

#634 Feature/disable app insights on local - DON'T MERGE FOR NOW
  api/controllers/case-list/index.ts
  api/lib/appInsights.ts
  api/lib/log4jui.ts
  api/lib/processors/case-state-model.ts
  application.ts
Labels: ns:jui-webapp-pr-634

#642 recode
  api/controllers/case-list/index.ts
Labels: ns:jui-webapp-pr-642

#643 Adding web config
  Web.Config
Labels: ns:jui-webapp-pr-643

#644 Rename Web.Config to web.Config
  web.Config
Labels: ns:jui-webapp-pr-644

#645 Delete web.Config
  web.Config
Labels: ns:jui-webapp-pr-645

#647 Update prod.config.ts
  config/environments/prod.config.ts
Labels: ns:jui-webapp-pr-647

#646 added PV states
  api/controllers/case-list/index.ts
  api/lib/appInsights.ts
  api/lib/interceptors.ts
  api/lib/log4jui.ts
  api/lib/processors/case-state-model.ts
  api/lib/processors/case-state-util.ts
  api/services/coh.ts
  application.ts
Labels: ns:jui-webapp-pr-646

#650 Update prod.config.ts
  config/environments/prod.config.ts
Labels: ns:jui-webapp-pr-650

#648 removed hardcoded debugging
  api/lib/processors/case-state-util.ts
Labels: ns:jui-webapp-pr-648

#653 Master test remove some console.logs
  api/controllers/decisions/divorce/index.ts
  api/controllers/documents/index.ts
  api/lib/errorStack.ts
  api/services/coh.ts
Labels: ns:jui-webapp-pr-653

#654 Testing app insights
  api/lib/appInsights.ts
Labels: ns:jui-webapp-pr-654

#656 Update prod.config.ts
  config/environments/prod.config.ts
Labels: ns:jui-webapp-pr-656

#657 Update appInsights.ts
  api/lib/appInsights.ts
Labels: ns:jui-webapp-pr-657

#661 adding zone import for test
  src/polyfills.ts
Labels: ns:jui-webapp-pr-661

#662 Removing health check for test purpose
  application.ts
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-662

#663 fixing link bug
  api/package.json
  src/app/routing/pages/decisions/check-decision/check-decision.component.html
Labels: ns:jui-webapp-pr-663

#665 disable app insights on prod
  api/lib/appInsights.ts
Labels: ns:jui-webapp-pr-665

#666 Update app insights
  api/lib/appInsights.ts
  application.ts
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-666

#664 Tests added to cover 'api/controllers/case-list/'
  api/controllers/case-list/assignCase.ts
  api/controllers/case-list/index.spec.ts
  api/controllers/case-list/index.ts
  api/controllers/questions/index.ts
  api/services/idam-api/idam-api.ts
Labels: ns:jui-webapp-pr-664

#669 Add in health
  api/lib/appInsights.ts
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-669

#671 idam recode
  api/controllers/auth/index.ts
  api/controllers/case-list/assignCase.ts
  api/controllers/case-list/index.spec.ts
  api/controllers/case-list/index.ts
  api/index.ts
  api/lib/filters.ts
  api/services/idam.ts
Labels: ns:jui-webapp-pr-671

#668 Bug/em 1140 highlighting text inaccurate bug
  src/public/javascripts/pdf-annotate.js
  src/public/javascripts/pdf.js
Labels: ns:jui-webapp-pr-668

#672 fixing links
  src/app/routing/pages/decisions/check-decision/check-decision.component.html
Labels: ns:jui-webapp-pr-672

#655 userId replaced with name
  api/controllers/case/index.ts
  api/controllers/decisions/cohDecisions.ts
  api/controllers/events/index.ts
  api/controllers/questions/index.ts
  api/lib/util.ts
  api/services/coh-cor-api/coh-cor-api.ts
Labels: ns:jui-webapp-pr-655

#674 recode of service auth
  api/index.ts
  api/lib/middleware/service-token.ts
  api/services/service-auth-provider-api/service-auth-provider-api.ts
  api/services/serviceAuth.ts
Labels: ns:jui-webapp-pr-674

#673 Bug/em 1140 highlighting text inaccurate bug
  src/public/javascripts/pdf-annotate.js
  src/public/javascripts/pdf.js
Labels: ns:jui-webapp-pr-673

#676 added isCorDecision
  api/controllers/decisions/sscs/index.ts
Labels: ns:jui-webapp-pr-676

#675 update judge name
  api/lib/config/refJudgeLookUp.crypt
  api/lib/encryption.ts
Labels: ns:jui-webapp-pr-675

#680 Bug/fix error on error logging when session fails
  api/controllers/case-creation/index.ts
  api/index.ts
  api/lib/errorStack.ts
  api/lib/interceptors.ts
  api/lib/middleware/service-token.ts
  api/lib/util.ts
  api/services/serviceAuth.ts
  application.ts
Labels: ns:jui-webapp-pr-680

#681 RIUI-1460 Fixed
  src/app/domain/components/questions/create/create.component.ts
Labels: ns:jui-webapp-pr-681

#684 Add unit test for error interceptor
  api/lib/interceptors.spec.ts
  api/lib/interceptors.ts
Labels: ns:jui-webapp-pr-684

#689 fix interceptor
  api/controllers/case-list/index.ts
Labels: ns:jui-webapp-pr-689

#692 questions regression
  api/controllers/case-list/index.spec.ts
  api/controllers/case-list/index.ts
Labels: ns:jui-webapp-pr-692

#693 authenticate timeout
  api/lib/middleware/auth.ts
Labels: ns:jui-webapp-pr-693

#696 Delete prod.config.js
  config/environments/prod.config.js
Labels: ns:jui-webapp-pr-696

#695 Unit tests for 'api/controllers/case'
  api/controllers/case/index.spec.ts
  api/controllers/case/index.ts
  api/controllers/case/templates/index.ts
  api/lib/processors/value-processor.ts
Labels: ns:jui-webapp-pr-695

#697 bug/ bug in auth
  api/index.ts
  api/lib/middleware/auth.ts
  api/lib/middleware/service-token.ts
  package-lock.json
  package.json
  src/app/auth/auth.service.ts
  yarn.lock
Labels: ns:jui-webapp-pr-697

#699 Chore/retry ccd if caselists fail
  api/controllers/case-list/index.ts
  config/application.config.ts
Labels: ns:jui-webapp-pr-699

#701 Test for prod
  application.ts
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-701

#703 better error handing
  api/controllers/case-list/index.ts
  api/controllers/events/index.ts
Labels: ns:jui-webapp-pr-703

#707 RIUI-1504 fixed
  api/controllers/decisions/sscs/templates/benefit/check.ts
  api/controllers/decisions/sscs/templates/benefit/checkTribunal.ts
Labels: ns:jui-webapp-pr-707

#708 enable_smoke_tests
  test/e2e/config/conf.js
  test/e2e/config/smoke.conf.js
Labels: ns:jui-webapp-pr-708

#715 remove angular univeral from app
  api/controllers/auth/index.ts
  api/lib/middleware/auth.ts
  api/lib/middleware/service-token.ts
  api/package.json
  application.ts
  config/application.config.ts
  config/index.ts
  dev-server.ts
  local.ts
  package-lock.json
  package.json
  server.ts
  src/app/app.component.ts
  src/app/config.service.ts
  src/app/domain/services/case.service.ts
  src/app/routing/pages/decisions/root/root.component.spec.ts
  src/app/routing/routing.module.ts
  test/e2e/features/step_definitions/steps/dashBoard.steps.js
  test/e2e/features/step_definitions/steps/logIn.steps.js
  test/e2e/support/constants.js
  yarn.lock
Labels: ns:jui-webapp-pr-715

#721 Revert "remove angular univeral from app"
  api/controllers/auth/index.ts
  api/lib/middleware/auth.ts
  api/lib/middleware/service-token.ts
  api/package.json
  application.ts
  config/application.config.ts
  config/index.ts
  dev-server.ts
  local.ts
  package-lock.json
  package.json
  server.ts
  src/app/app.component.ts
  src/app/config.service.ts
  src/app/domain/services/case.service.ts
  src/app/routing/pages/decisions/root/root.component.spec.ts
  src/app/routing/routing.module.ts
  test/e2e/features/step_definitions/steps/dashBoard.steps.js
  test/e2e/features/step_definitions/steps/logIn.steps.js
  test/e2e/support/constants.js
  yarn.lock
Labels: ns:jui-webapp-pr-721

#723 Remove angular universal
  api/controllers/auth/index.ts
  api/lib/middleware/auth.ts
  api/lib/middleware/service-token.ts
  api/package.json
  application.ts
  config/application.config.ts
  config/index.ts
  dev-server.ts
  local.ts
  package-lock.json
  package.json
  server.ts
  src/app/app.component.ts
  src/app/config.service.ts
  src/app/domain/services/case.service.ts
  src/app/routing/pages/decisions/root/root.component.spec.ts
  src/app/routing/routing.module.ts
  test/e2e/config/conf.js
  test/e2e/config/smoke.conf.js
  test/e2e/features/app/dashBoard.min.feature
  test/e2e/features/pages/loginPage.js
  test/e2e/features/step_definitions/steps/dashBoard.steps.js
  test/e2e/features/step_definitions/steps/logIn.steps.js
  test/e2e/support/constants.js
  test/e2e/support/timeout.js
  yarn.lock
Labels: ns:jui-webapp-pr-723

#717 Bug/em 1158 re render when highlight removed
  src/app/shared/components/hmcts-em-viewer-ui/data/annotation-store.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/data/pdf-render.service.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/annotation-pdf-viewer.component.html
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/annotation-pdf-viewer.component.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/contextual-toolbar/contextual-toolbar.component.spec.ts
  src/app/shared/components/hmcts-em-viewer-ui/viewers/annotation-pdf-viewer/contextual-toolbar/contextual-toolbar.component.ts
  src/public/javascripts/pdf-annotate.js
Labels: ns:jui-webapp-pr-717

#714 points spelling fixed
  api/controllers/decisions/sscs/templates/benefit/budgetingDecisions.ts
  api/controllers/decisions/sscs/templates/benefit/communicatingVerbally.ts
  api/controllers/decisions/sscs/templates/benefit/dressingUndressing.ts
  api/controllers/decisions/sscs/templates/benefit/engagingFace.ts
  api/controllers/decisions/sscs/templates/benefit/managingToilet.ts
  api/controllers/decisions/sscs/templates/benefit/movingAround.ts
  api/controllers/decisions/sscs/templates/benefit/planningJourneys.ts
  api/controllers/decisions/sscs/templates/benefit/readingSigns.ts
  api/controllers/decisions/sscs/templates/benefit/washingBathing.ts
Labels: ns:jui-webapp-pr-714

#716 removal of sticky to assist with selecting documents
  src/public/components/casefile/_casefile-3.scss
Labels: ns:jui-webapp-pr-716

#732 Chore/update deps
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-732

#728 Fuller coverage for 'api/controllers/questions/'
  api/controllers/questions/index.spec.ts
  api/controllers/questions/index.ts
  api/index.ts
Labels: ns:jui-webapp-pr-728

#735 remove bable and regenerate
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-735

#725 demo component deleted, FR-499 fixed.
  src/app/domain/components/search-result/search-result.component.spec.ts
  src/app/domain/services/case.service.ts
  src/app/routing/pages/generic-page/demo/demo.component.html
  src/app/routing/pages/generic-page/demo/demo.component.ts
  src/app/routing/routing.module.ts
Labels: ns:jui-webapp-pr-725

#736 no ng tunnel
  api/lib/http/index.ts
  api/lib/request/proxy.ts
  api/lib/request/request.ts
  application.ts
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-736

#737 Revert "no ng tunnel"
  api/lib/http/index.ts
  api/lib/request/proxy.ts
  api/lib/request/request.ts
  application.ts
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-737

#713 Change asp for prod test
  infrastructure/main.tf
Labels: ns:jui-webapp-pr-713

#744 manual install with verbose logging - DO NOT MERGE
  Jenkinsfile_CNP
Labels: ns:jui-webapp-pr-744

#747 Bug/riui 1515 jui sscs answers were not showing up
  api/controllers/questions/index.spec.ts
  api/controllers/questions/index.ts
  yarn.lock
Labels: ns:jui-webapp-pr-747

#733 SSCS and Auth coverage
  api/controllers/auth/index.spec.ts
  api/controllers/decisions/sscs/index.spec.ts
Labels: ns:jui-webapp-pr-733

#709 Chore/redirect on invalid session
  api/controllers/auth/index.spec.ts
  api/controllers/auth/index.ts
  api/lib/middleware/auth.ts
  src/app/app.interceptor.ts
  src/app/app.module.ts
Labels: ns:jui-webapp-pr-709

#751 disable sonar as ng tests coverage is dropped
  sonar-project.properties
Labels: ns:jui-webapp-pr-751

#754 Revert "manual install with verbose logging - DO NOT MERGE"
  Jenkinsfile_CNP
Labels: ns:jui-webapp-pr-754

#752 Adding package to see if it gets stripped out.
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-752

#756 Adding proxy package as test
  package-lock.json
  package.json
  yarn.lock
Labels: ns:jui-webapp-pr-756

#759 Adding more memory
  charts/jui-webapp/values.template.yaml
Labels: ns:jui-webapp-pr-759

#757 table component unit test fixed
  src/app/domain/components/questions/check/check.component.ts
  src/app/shared/components/table/mock/table.mock.ts
  src/app/shared/components/table/table.component.spec.ts
  src/app/shared/components/table/table.component.ts
Labels: ns:jui-webapp-pr-757
